Scripts/Models/Nieuwenhuis2005Model.py

fixed bug in plotting Nieuwenhuis Model

---

README.rst
docs/source/index.rst
docs/source/index_logo_with_text.rst
postBuild

- add postBuild file for tutorial dependencies
- add badge to readme to link to mybinder
- update tutorial documentation

tutorial: support execution on mybinder.org

---

psyneulink/components/process.py
psyneulink/components/system.py
psyneulink/globals/environment.py

Just removing a few confusing print statements and adding a comment to watch out for multiple target mechanisms.

Target fixes

---

Scripts/Examples/Rumelhart Semantic Network.py
psyneulink/components/system.py

This reverts commit a75aeb0659fc82d5d99812d63ce09323c4939d71.

Revert "Fix/system/learning ends before terminal (#685)"

---

psyneulink/components/functions/function.py
psyneulink/components/mechanisms/adaptive/control/controlmechanism.py

• Function
SoftMax: cleaned-up _instantiate_function and function to use one_hot for PROB

Clean up/function/softmax one hot

---

psyneulink/components/functions/function.py
psyneulink/components/mechanisms/adaptive/control/controlmechanism.py
psyneulink/components/mechanisms/mechanism.py
psyneulink/components/states/outputstate.py

• Mechanism
added MechParamsDict as dict subclass
• OutputState
_parse_variable_spec: checks that dicts passed to it are MechParamsDict

Refactor/mechanism and output state/mech params dict added

---

psyneulink/components/functions/function.py
psyneulink/components/mechanisms/adaptive/learning/learningauxilliary.py

• Function
Incorporate changes to LearningFunctions from old closed PR:
- remove activation_function from constructors
- docstring revs

• Function

---

Scripts/Examples/Rumelhart Semantic Network.py
psyneulink/components/system.py

• System
show_graph():  
- minor bug fix show System Target Inputs
- changed label of System node to <System.name> Target Input

• fix_system_show_graph_w_structure

---

.idea/runConfigurations/py_test_for_tests_control_test_EVC_test_EVC.xml
psyneulink/components/component.py
psyneulink/components/mechanisms/adaptive/gating/gatingmechanism.py
psyneulink/components/mechanisms/adaptive/learning/learningmechanism.py
psyneulink/components/mechanisms/mechanism.py
psyneulink/components/mechanisms/processing/objectivemechanism.py
psyneulink/components/process.py
psyneulink/components/projections/modulatory/controlprojection.py
psyneulink/components/projections/modulatory/gatingprojection.py
psyneulink/components/projections/modulatory/learningprojection.py
psyneulink/components/projections/modulatory/modulatoryprojection.py
psyneulink/components/projections/pathway/mappingprojection.py
psyneulink/components/projections/pathway/pathwayprojection.py
psyneulink/components/projections/projection.py
psyneulink/components/states/inputstate.py
psyneulink/components/states/modulatorysignals/controlsignal.py
psyneulink/components/states/modulatorysignals/modulatorysignal.py
psyneulink/components/states/outputstate.py
psyneulink/components/states/parameterstate.py
psyneulink/components/states/state.py
psyneulink/components/system.py

• Context
- initialization_status.UNSET -> initialization_status.INITALIZING
where appropriate
- delete InitStatus class

Removed UNSET and InitStatus

---

.travis.yml

Needed for "dot" command
Fixes travis runs

travis: Add graphviz package

---

Scripts/Kalanthroff_PCTC_2018.py

Implemented Stroop model by Kalanthroff&Usher 2018

new script

---

docs/source/Cohen_HustonModel.rst

changed figure size in docs to 45%

changed figure sizeto 45%

---

.travis.yml

There might be a more efficient way to do this, rather than install everything via brew, but this is enough to pass the test suite.

add macos builds to travis

---

psyneulink/components/component.py
psyneulink/globals/context.py
psyneulink/globals/log.py
psyneulink/globals/utilities.py

- Generalize __deepcopy__ method that allows "partial" deepcopy (i.e. some keys are shared, like "owner")
- Enable deepcopying of
- Log
- Context

Improve deepcopy

---

psyneulink/globals/context.py

- imports cleanup
- allow more types of Compositions to be assigned to Context object
- add method to set or append to string depending on its current contents

Context: various improvements

---

setup.cfg

pytest-cov: Add basic line exclude regular expressions

---

psyneulink/components/system.py

solves python3.7 compatibility

System: correct string comparison during detection of monitored output states

---

psyneulink/components/functions/function.py
tests/functions/test_distance.py
tests/mechanisms/test_contrastive_hebbian_mechanism.py

functions/DistanceFunction: MAX_DIFF should apply abs first, then max

---

.appveyor.yml

.appveyor: Simplify test run command

---

psyneulink/compositions/__init__.py
psyneulink/compositions/pytorchmodelcreator.py
tests/composition/test_autodiffcomposition.py

Dcw torch import fix

---

.appveyor.yml

.appveyor: reenable 32bit tests

---

.appveyor.yml

Fixes permission problems in recent appveyor runs.

appveyour: Install packages in user repo

---

.appveyor.yml

appveyor: Export junit tests

---

.idea/runConfigurations/py_test_in_tests.xml
psyneulink/core/components/functions/function.py
tests/composition/test_control.py

• test_control:
added function assignments with max_iterations=1

Limit iterations on LVOCControlMechanism tests

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/library/components/mechanisms/adaptive/control/lvoccontrolmechanism.py

- exeucte:  deleted calls to _increment_execution_count and
_update_current_execution_time since handled by Component
(and was causing excess increments)

• Mechanism

---

setup.cfg

• setup.cfg

---

.travis.yml

Cache the entire python virtual env.
Cache homebrew download folder.

travis osx improvements

---

psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py

• OptimizationControlMechanism
- objective_function -> evaluation_function

Refactor/opt ctl mech/obj fct to eval fct

---

tests/functions/test_combination.py
tests/models/test_greedy_agent.py

Split LinearCombination tests.
Add simplified GreedyAgent model benchmark.

Add simplified GreedyAgent model benchmark.

---

.travis.yml

Make sure we always use the latest version.

.travis: Don't cache installed python modules

---

setup.cfg

setup.cfg: Skip coverage checking private debug_env

---

.travis.yml

travis: Update setuptools-scm to avoid TLS protocol issue

---

Scripts/Models (Under Development)/Predator-Prey Model DQN.py
Scripts/Models (Under Development)/Predator-Prey Model INPUT LAYER.py
Scripts/To Debug/StabilityFlexibility.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/objectivemechanism.py
psyneulink/core/components/states/inputstate.py
psyneulink/core/compositions/composition.py

• InputState
  _instantiate_input_states:  added support for SHADOW_INPUTS spec
• InputState, ObjectiveMechanism and OptimizationControlMechanism
  - docstring mods re: SHADOW_INPUTS

Feat/input state/shadow inputs

---

.idea/runConfigurations/Make_HTML.xml
psyneulink/core/components/states/inputstate.py

Docs/input state/shadow input

---

Scripts/To Debug/Umemoto_Feb.py
psyneulink/core/components/functions/optimizationfunctions.py

• SampleSpec, SampleIterator
- add use of decimal module to handle decimal start and stop values;
ensures sensible enforcement and treatment of num attribute as int;
includes specification of precision at module level

• SampleSpec, SampleIterator

---

.travis.yml

travis: Don't run or install coveralls if the repo token is not set

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py
psyneulink/core/compositions/composition.py
tests/models/test_greedy_agent.py

Add basic compilation support for compositions with controllers

---

.appveyor.yml

This is set up in the appveyor project

appveyor: Drop branch whitelist

---

psyneulink/core/compositions/composition.py
psyneulink/core/compositions/pathwaycomposition.py
psyneulink/library/compositions/autodiffcomposition.py

These changes reduce the amount of extraneous copying of data between execution contexts, especially for simulations.

Optimize instantiation of execution contexts for Compositions

---

psyneulink/core/components/functions/optimizationfunctions.py
tests/composition/test_control.py

Fix probability bug and add pytest

Feat/grid search/choose randomly from identical values

---

psyneulink/core/components/functions/learningfunctions.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/globals/utilities.py
tests/composition/test_models.py
tests/no-learning/test_stroop_no_learning.py

NUmpy matrix is deprecated since 1.15

Remove most uses of np.matrix

---

tests/mechanisms/test_recurrent_transfer_mechanism.py

tests/mechanisms/RecurrentTransferMechanism: Split matrix spec tests

---

Scripts/Debug/Bustamante_Stroop_XOR_LVOC_Model_NOT_AS_OLD.py
Scripts/Examples/Composition/EVC-Gratton Composition.py
Scripts/Models (Under Development)/Predator-Prey Model DQN.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py

added gradient_function as argument to constructor

• OptimizationFunction

---

Scripts/Debug/build_input.py

• Scripts/Debug:
added build_input.py needed for Bustamante_Stroop_XOR_LVOC_Model

• Scripts/Debug:

---

tests/mechanisms/test_episodic_memory.py

... and pass it the correct probability parameters.

tests/mechanism/test_episodic_memory: Instantiate DND function explictly

---

psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py

- ContentAddressableMemory:  docstring mods

• MemoryFunctions

---

.appveyor.yml

Should help workaround intermittent network issues.

appveyor: Add appveyor-retry to chcolatey and results upload

---

setup.cfg

code coverage: Omit models directory

---

.appveyor.yml
.travis.yml
conftest.py
dev_requirements.txt
setup.cfg
tests/models/test_botvinick.py

Register all used markers.
Fix check for stress marker.
Convert botvinick test to use parameter stress markers.

Enable pytest>=4

---

.appveyor.yml

Appveyor already builds pull requests.

appveyor: Restrict built branches again.

---

.travis.yml
dev_requirements.txt

Fails to enumerate leabra tests.

Retrict pytest to '<4.6'

---

.travis.yml

travis: Cache downloaded apt packages

---

.appveyor.yml
psyneulink/core/llvm/jit_engine.py

llvm: Change relocation model to static and enable llvmlite>=0.27

---

.travis.yml

Add more details in the comment.

travis: Remove pytest version restriction

---

psyneulink/core/components/functions/learningfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/states/inputstate.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/socket.py

treewide: Fix imports from collections

---

.appveyor.yml

appveyor: switch graphviz from chocolatey to msi install

---

.appveyor.yml
.travis.yml
dev_requirements.txt

requirements, travis, appveyor: Restrict pytest<5.

---

.travis.yml

travis: Bump python-3.7 version to 3.7.4

---

dev_requirements.txt
psyneulink/core/components/mechanisms/adaptive/learning/learningmechanism.py
psyneulink/core/globals/utilities.py
setup.cfg
tests/composition/test_learning.py

The list of error conditions:
http://www.pydocstyle.org/en/3.0.0/error_codes.html

Travis docstrings avy

---

psyneulink/core/compositions/composition.py

Updated docstrings related to 
1. adding Compositions as nodes of other Compositions 
and 
2. modulating parameters of nodes of nested compositions with enclosing Composition's controller

Nested Composition, Control of Nested Node Parameter Docstrings

---

.travis.yml

Avoids reupload on changes to unrelated files in ~/Library/Cache.

travis, macos: Split cache and list hombrew and pip explicitly

---

.appveyor.yml

appveyor: Consolidate graphviz version in one place

---

.idea/runConfigurations/Make_HTML.xml
docs/source/BasicsAndSampler.rst

• BasicsAndSampler
added section on UDF

• BasicsAndSampler

---

psyneulink/core/components/mechanisms/adaptive/control/controlmechanism.py
psyneulink/core/compositions/composition.py
tests/composition/test_learning.py
tests/learning/test_rumelhart_semantic_network.py

docstyle: Fix invalid escape sequences

---

.travis.yml

travis: Downgrade numpy early if needed

---

psyneulink/core/components/mechanisms/adaptive/modulatorymechanism.py
psyneulink/core/components/states/inputstate.py
psyneulink/core/components/states/outputstate.py
psyneulink/core/components/states/parameterstate.py

docstrings: Consistently use triple double quotes

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/objectivemechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/process.py
psyneulink/core/components/projections/pathway/mappingprojection.py
psyneulink/core/components/projections/projection.py
psyneulink/core/components/states/modulatorysignals/controlsignal.py
psyneulink/core/components/states/state.py
psyneulink/core/components/system.py
psyneulink/core/compositions/composition.py
psyneulink/library/components/mechanisms/adaptive/control/evc/evccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/compositions/gymforagercfa.py
psyneulink/library/compositions/regressioncfa.py

- _dependent_components no longer need to be specified for Components listed in a class's Parameters

Auto-detect Parameters to be included in _dependent_components

---

psyneulink/core/components/mechanisms/adaptive/modulatorymechanism.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/states/parameterstate.py
psyneulink/core/components/states/state.py
psyneulink/core/compositions/composition.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/composition/test_gating.py
tests/functions/test_default_allocation.py

Allow any state to take modulatory input.

llvm: Add support for gating modulation

---

tests/functions/test_identity.py
tests/llvm/test_builtins_vector.py
tests/llvm/test_debug_composition.py
tests/llvm/test_helpers.py
tests/models/test_botvinick.py
tests/models/test_greedy_agent.py

Drop few unused imports

---

.travis.yml

travis: let coveralls figure out the travis environment

---

.appveyor.yml
dev_requirements.txt
requirements.txt

Reorganize and sort.
Restrict torch to Linux and macOS

Cleanup requirements

---

tests/models/test_bi_percepts.py

tests/simplified necker cube: Make all variables local to the test

---

.travis.yml

travis: Cleanup and comment

---

Scripts/Debug/Predator-Prey Sebastian REDUCED.py
Scripts/Debug/Predator-Prey Sebastian.py
psyneulink/core/compositions/composition.py

• Composition
- show_graph: fixed bug causing crash if Composition had a controller

• Composition

---

psyneulink/core/globals/utilities.py

utilities: Simplify deepcopy with shared

---

.travis.yml

This can be set/unset in travis settings.

travis: Condition coverage checks on global environment variable

---

psyneulink/core/components/functions/function.py

function: Reseed random state when copying functions.

---

setup.cfg

docstyle: Allow checks on __init__.py files

---

tests/misc/test_notebooks.py

List notebook name as parameter.
Resue the same python interpreter as the one running the pytest.
Set `PYHTONPATH` env var to access the tested instance of psyneulink.

Refactor tutorial pytest

---

.appveyor.yml

appveyor: Remove python package workarounds

---

conftest.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/selectionfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_autodiffcomposition.py
tests/functions/test_memory.py
tests/json/test_json.py
tests/llvm/test_builtins_random.py
tests/mechanisms/test_integrator_mechanism.py

Use numpy random instead.
Cleanup private random_state parameters.

Avoid using Python 'random' module

---

.travis.yml

travis: Install python 3.8 from bionic main

---

psyneulink/core/compositions/composition.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/compiledloss.py
psyneulink/library/compositions/compiledoptimizer.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/composition/test_autodiffcomposition.py

llvm: Cleanup compilation support for pytorch/autodiff

---

.github/workflows/pnl-ci.yml

Princeton University disabled 3rd party actions (which includes all github actions)

Stop using GitHub actions

---

.github/workflows/pnl-ci.yml
.travis.yml

wheels for other OSes are not available yet

Fix github-actions issues, enable pytorch on python 3.8 on Linux

---

psyneulink/library/compositions/autodiffcomposition.py

Add warning to docs for issue (#1461)

autodiffcomp: Add warning to docs (#1461)

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/helpers.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_recurrent_transfer_mechanism.py

Add support for AtTrial and AtPass scheduling conditions.

llvm: Add support for 'reinitialize_when' feature

---

psyneulink/core/compositions/composition.py
psyneulink/core/llvm/execution.py
psyneulink/library/compositions/autodiffcomposition.py

llvm: Consider only inner projections in compiled structures

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/helpers.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/compositions/compiledoptimizer.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/llvm/test_helpers.py
tests/mechanisms/test_recurrent_transfer_mechanism.py

Fix counting of iterations_until_finished to match python PNL.
Cleanup.

llvm: Do not reinitialize if 'hsa_initializers' is False

---

tests/composition/test_composition.py

Adds an additional test for PR #1474

tests/composition: Add test for nested run with differing num trials

---

.github/workflows/pnl-ci.yml
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/functions/test_integrator.py

Reuse Component generated structures as much as possible.

llvm: Flatten mechanism compiled structures

---

psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
tests/mechanisms/test_ddm_mechanism.py

Matches python behaviour.
Add test.

llvm, functions/StatefulFunction: Add random state hack to llvm code

---

.appveyor.yml
.travis.yml
psyneulink/library/compositions/__init__.py
setup.cfg

Cleanup imports.
Extend appveyor win32 to run python tests.

library/compositions: Allow composition runner without pytorch

---

psyneulink/core/compositions/composition.py
psyneulink/library/compositions/autodiffcomposition.py

docs/learning: Remove unnecessary details from `AutodiffComposition`

---

psyneulink/library/compositions/autodiffcomposition.py
tests/composition/test_autodiffcomposition.py

Adds a quick test that checks to make sure losses are being tracked

tests/autodiff: Add test for loss tracking

---

psyneulink/core/compositions/composition.py
psyneulink/core/globals/log.py
tests/log/test_log.py

If multiple entries exist in a log for a single Time, the last one will be reported in Logging helper methods (was previously the first)

Log: Handling of multiple entries at same Time for given param

---

tests/mechanisms/test_transfer_mechanism.py

• tests/mechanisms/test_transfer_mechanism

---

.travis.yml

Timeouts often.
macOS is tested both by github-actions and jenkins

travis: Drop testing on osx

---

.travis.yml

travis: Cleanup osx cache locations

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/helpers.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py

Cache compilation param/state ids.

llvm: Follow python 'is_finished_flag' semantics more closely

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/codegen.py

Cleanup. Drop dead code.
Closes: #1479

llvm: Use named indices to composition state and param structures

---

.github/workflows/pnl-ci.yml

github-actions: Always run tests in parallel

---

psyneulink/core/llvm/helpers.py
tests/composition/test_composition.py

This pull adds compiled variants of:
1. BeforeNCalls
2. AtNCalls
3. AfterNCalls
4. WhenFinishedAny
5. WhenFinishedAll
6. Not

llvm: Add various new compiled conditions

---

tests/api/test_api.py

Added file for testing the API. Will be used for tracking changes that break previous API functionality.

tests/api: add test file for tracking changes to API

---

.github/workflows/pnl-ci.yml

github-actions: Enable python3.8 windows run

---

.travis.yml

This helps prevent unbound cache growth.

travis: Cleanup old wheels from pip cache

---

psyneulink/library/compositions/compositionrunner.py

autodiffcomposition: Don't use python random

---

.travis.yml

travis: Disable coverage on non-x86 archs

---

.travis.yml

travis: Export global env vars

---

.travis.yml

travis: Allow ppc64le jobs to fail

---

docs/source/Component.rst
psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/ports/port.py
psyneulink/core/components/projections/projection.py

• Component, Mechanism, Port, Projection:
- docstring:  added "shadow" argument declaration to constructors

Docs/base classes/docstring args

---

setup.cfg
setup.py

Bump coverage requirement to 75%

setup: Update required/supported python versions

---

psyneulink/core/globals/context.py

- added PREPARING flag to EXECUTION_PHASE group
(for use with _animate and checking for deferred_init projections)

• context.py

---

psyneulink/core/compositions/composition.py

- show_graph(): 
added cycle_shape (defaults to doublecircle)
projections to/from parameter_CIM fixed

Feat/show graph/cycle shape

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/compositions/composition.py

  - show_graph():  fixes bugs in parameter_CIM projections to nested comps

Fix/show graph/parameter cim projections

---

.travis.yml

Building wheels can take a long time.

travis: Add precache stage for ppc64le

---

psyneulink/core/components/component.py

Skip over aliases and handle with main parameter.
If an alias was encountered before its source Parameter when iterating through
parameter names, and the value for the source was user-specified, this value
would be copied when it would have been directly assigned as the Parameter
value.
Visible in tests/functions/test_buffer.py::test_buffer_standalone_noise_function
The NormalDist function assigned as noise should not be copied because it has no
owner. When 'additive_param' was encountered first, the function would be
copied.

Component: _initialize_parameters: handle iter order of parameters with aliases

---

.travis.yml

travis: Add arm64 jobs

---

psyneulink/core/components/functions/userdefinedfunction.py
tests/composition/test_composition.py
tests/functions/test_user_defined_func.py

llvm, functions/UserDefinedFunction: Add python callback implementation of UDF

---

.travis.yml

travis: Streamline maintenance of pip wheel cache

---

tests/composition/test_composition.py
tests/composition/test_control.py
tests/composition/test_interfaces.py
tests/functions/test_buffer.py
tests/functions/test_memory.py
tests/mechanisms/test_contrastive_hebbian_mechanism.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/misc/test_utilities.py
tests/ports/test_output_ports.py

Cleanup uses of benchmark fixture and pytest.warns.

tests: Cleanup

---

.travis.yml

travis: Restrict arm64 to 16 runners

---

.github/workflows/pnl-ci.yml

github-actions: Restrict pytest to max 2 processes

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py

Refactor to make better use of existing shared routines.

llvm: Cleanup

---

psyneulink/core/components/functions/learningfunctions.py

Occurs when learning_rate is 1d

[Contrastive]Hebbian: fix bug causing double multiplication of learning_rate

---

.github/dependabot.yml
.github/workflows/pnl-ci.yml

Automatically update github-actions.

github-actions: Enable automatic updates of used actions

---

psyneulink/core/components/component.py
tests/functions/test_user_defined_func.py
tests/llvm/test_helpers.py

llvm/cuda, tests: Make udf and helper tests CUDA friendly

---

.travis.yml

travis: Bump llvm version to 10

---

tests/models/test_greedy_agent.py

tests/models/predator-prey: Sort by number of attention levels

---

requirements.txt

elfi depends on networkx and needs to be updated in sync

requirements: update elfi and networkx

---

psyneulink/core/llvm/jit_engine.py

llvm/jit_engine: Enable loop vectorizer

---

requirements.txt

- update grpcio-tools requirement from <=1.31.0 to <1.34.0
- update grpcio requirement from <=1.31.0 to <1.34.0

Bump GRPC-related requirement versions

---

.travis.yml

travis: Install leabra after other dependencies

---

.github/workflows/pnl-ci.yml

github-actions: Comment and formatting

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/library/components/mechanisms/processing/transfer/lcamechanism.py
tests/composition/test_control.py
tests/mechanisms/test_transfer_mechanism.py

See message of b7a4d5a47452c5c6b1e3728258ea1ae487480a24 for `test_recurrent_control` value change

Simplify creation and execution of TransferMechanism.integrator_function

---

.github/workflows/pnl-ci.yml
.travis.yml
leabra_requirements.txt
setup.py

deps: Convert leabra to 'extra' dependency

---

Scripts/Debug/Yotam LCA Model.py

This is the fix for Yotam's LCA model
The main changes were syntactic, to account for updates to learning syntax and input parsing.

Scripts: Update Yotam's LCA Model

---

.travis.yml

travis: Explicitly install undeclared dependency on cython

---

.github/workflows/pnl-ci.yml
.travis.yml
psyneulink/library/components/mechanisms/processing/leabramechanism.py
requirements.txt
tests/mechanisms/test_leabra_mechanism.py

Add `leabra` to `requirements.txt` and remove special casing from before the package was on PyPi

deps: Add leabra as dependency to PsyNeuLink

---

.travis.yml

travis: Install numpy early on x86

---

.github/workflows/pnl-ci.yml

Fixes issues with mismatched ABI.

github-actions: Install numpy explicitly ahead of other packages

---

.travis.yml

travis: Disable ppc64le runs

---

dev_requirements.txt
doc_requirements.txt
setup.py

requirements: Move doc requirements to a separate file

---

docs/source/Compilation.rst
docs/source/Core.rst
docs/source/Services.rst

documentation: Add a short overview of PsyNeuLink compiltion

---

.github/workflows/pnl-ci-docs.yml
psyneulink/core/components/ports/inputport.py

Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/1870

documentation: Fix python 3.8/3.9 builds

---

psyneulink/core/compositions/composition.py
psyneulink/core/llvm/helpers.py
psyneulink/core/scheduling/condition.py
tests/composition/test_composition.py

Implements `Any` scheduling condition and add time scale support to `AllHaveRun`.
Enable `AtPass` test.
Closes: #1579

llvm: Use AllHaveRun instead of EveryNCall when compiling consideration queue

---

requirements.txt

requirements: Bump numpy to 1.20.1

---

psyneulink/library/components/mechanisms/processing/leabramechanism.py

Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/1802

LeabraMechanism: standardize function creation, make network FunctionParameter

---

psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/core/llvm/helpers.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_autodiffcomposition.py
tests/llvm/test_builtins_intrinsics.py
tests/llvm/test_builtins_matrix.py
tests/llvm/test_helpers.py

Cleanup and consolidate tests.

llvm: Convert tanh, coth, csch, is_close to builtin functions

---

psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/library/components/mechanisms/processing/leabramechanism.py

Along with #1909 and #1911, solves #1802

LeabraFunction: make training_flag dependent on network

---

conftest.py
docs/source/Compilation.rst
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/compositionrunner.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_composition.py
tests/composition/test_control.py
tests/composition/test_interfaces.py
tests/llvm/test_debug_composition.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_lca.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/models/test_greedy_agent.py
tests/scheduling/test_scheduler.py

llvm, composition: Replace execution_mode string with enum.Flags

---

requirements.txt

requirements: Restrict rich to <9.13

---

psyneulink/core/globals/utilities.py

is_compatible(): if candidate and reference are both np.ndarrays, just check shape for efficiency.

• utilities.py

---

psyneulink/library/compositions/pytorchmodelcreator.py

in \_\_init\_\_, a full trial was run in the passed context, potentially messing up
future counts or clocks in that context

fix(PytorchModelCreator): use new context to init .execution_sets

---

docs/source/index.rst
docs/source/index_logo_with_text.rst

• added pronunciation key and acknowledgment of support to README and index_logo_with_text.rst

Docs/readme and index/pronunciation and support

---

psyneulink/core/scheduling/condition.py
psyneulink/core/scheduling/scheduler.py

Ensure creation by generic graph works, and allow more flexible input formats for conditions

Scheduler compatibility improvements

---

docs/source/index.rst
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py

• index.rst:  updated reference of Python 3.5 -> 3.6
• memoryfunctions.py
ContentAddressableMemory: add memory_num_entries property

Feat/content addressable memory/mem num entries

---

.github/actions/install-pnl/action.yml
.github/workflows/compare-comment.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml
setup.py

Drop python 3.6 CI jobs.
Bump python requirement.

Drop support for Python 3.6

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/compositions/composition.py
tests/functions/test_functions.py
tests/functions/test_user_defined_func.py

ensure reset after calling a Function alone, not just as part of another Component

components: consolidate reset of parameters overriden by runtime_params

---

psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/debug.py
psyneulink/core/llvm/jit_engine.py
tests/llvm/test_debug_composition.py

llvm: Add time profiling info for each step of the compilation pipeline

---

psyneulink/core/components/component.py

• Components - fixed typos in docstring

• Component - fix typos in docstring

---

.appveyor.yml

appveyor: Add code coverage CI config

---

requirements.txt

requirements: update pytorch requirement from <1.9.0 to <2.0.0

---

psyneulink/core/components/component.py
tests/components/test_general.py

returns a dict containing Parameters for all dependent components

Component: add all_dependent_parameters

---

.github/actions/install-pnl/action.yml
.github/workflows/pnl-ci-docs.yml

github-actions/install-pnl: Support persistent runners

---

tests/llvm/test_builtins_philox_random.py

Checks that our seed perturbation routine is correct
It's enough to test int64 since all other variants are derived from
int64.

tests/llvm: Add Philox PRNG tests with different seeds

---

.github/dependabot.yml

dependabot: Do not autorebase pending PRs

---

psyneulink/core/llvm/debug.py

llvm/debug: Document cuda_max_regs option

---

psyneulink/core/globals/parameters.py
tests/misc/test_parameters.py

fixes bug in which attributes of SharedParameter would not reference the
attributes on their source Parameter

SharedParameter improvements

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/nonstateful/distributionfunctions.py
psyneulink/core/components/functions/nonstateful/learningfunctions.py
psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/nonstateful/selectionfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py

functions: set fallback_default=True for seed parameter

---

psyneulink/core/llvm/jit_engine.py

llvm/jit_engine: Fix typo in debug option check

---

psyneulink/core/llvm/helpers.py
tests/llvm/test_helpers.py

Restrict graceful fail paths to library/symbol not found conditions.

llvm: Implement printf helper on windows

---

.github/actions/install-pnl/action.yml

github-actions/pnl-install: Check if a newly bumped dependency is rolled back during installation

---

.github/actions/install-pnl/action.yml

github-actions: Install latest pip and wheel when testing new dependencies

---

requirements.txt

requirements: update torch requirement from <1.9.0 to <1.12.0

---

requirements.txt

requirements: update pint requirement from <0.18 to <0.20

---

requirements.txt

requirements: update numpy requirement from <1.21.4 to <1.21.7

---

.github/actions/install-pnl/action.yml

github-actions/install-pnl: Move upgrade of pip+wheel to its own step

---

requirements.txt

requirements: update torch requirement from >=1.8.0,<1.12.0 to >=1.8.0,<1.13.0

---

.github/workflows/codeql.yml

Add config file and enable scanning on devel

Add CodeQL workflow for GitHub code scanning (#2533)

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py
tests/functions/test_transfer.py

Fixes SoftMax derivative on 2d input.
Clean tests.

function/SoftMax: Use correct dimensionality when calculating full Jacobian

---

psyneulink/core/globals/utilities.py

- iscompatible: replace initial test with safe_equals()
- safe_equals():  instantiate Katherine's mods + special handling of defaultdicts

• utilities.py:

---

conftest.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/library/compositions/autodiffcomposition.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_learning.py

• pnlvm.py
- ExecutionMode.PyTorch: make distinct from Python for warnings and errors
- learn(): add error for use of ExecutionMode.LLVM or ExecutionMode.PyTorch
• autodiffcomposition.py
- learn(): add warning for use of ExecutionMode.Python
• test_learning.py:
- add test_execution_mode_pytorch_and_LLVM_errors
• test_autodiffcomposition.py:
- add test_execution_mode_python_warning

ExecutionMode.PyTorch made distinct for warnings and errors

---

.github/actions/install-pnl/action.yml
requirements.txt

requirements: update torch requirement from >=1.8.0,<1.13.0 to >=1.8.0,<1.14.0

---

psyneulink/core/llvm/builtins.py
tests/llvm/test_builtins_mt_random.py
tests/llvm/test_builtins_philox_random.py

llvm/builtins: Implement binomial distribution for N==1

---

requirements.txt

requirements: Use upper and lower bound for fastkde

---

.github/actions/install-pnl/action.yml

github-actions: Generalize package name extraction from dependabot branch name

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/nonstateful/learningfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py

• function.py
- Function_Base:  
move arguments referring to parameters in call to function to params arg
(to be treated as runtime_params)
• memoryfunctions.py
- ContentAddressableMemory:  add store and retrieve convenience methods

• function.py

---

psyneulink/core/components/functions/stateful/integratorfunctions.py

as in 3a1d590a45db51dec600106b5226ffd54e6f15b9

OrnsteinUhlenbeckIntegrator: avoid producing 3d value

---

conftest.py
tests/composition/test_control.py
tests/models/test_greedy_agent.py

Both comp_mode, and ocm_mode need to be listed.

tests: Add helper to tests that include parallel compiled execution

---

psyneulink/core/components/component.py
psyneulink/core/compositions/composition.py
psyneulink/library/compositions/compositionrunner.py
tests/api/test_api.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_learning.py
tests/mechanisms/test_control_mechanism.py
tests/models/test_documentation_models.py

- add learning_results Parameter
- learn now returns single trial of results (to match run())
- docstrings mods accordingly
• compositionrunner.py:
- run_learning():
- return last trial of execution (to match calls to Composition.run()
- assign last epoch of results to Composition.learning_results

Tentative learning branch

---

tests/composition/test_autodiffcomposition.py
tests/functions/test_memory.py

Assert on the return value of equality.

tests: Use np.testing.assert_equal instead of np.all

---

psyneulink/core/compositions/composition.py
psyneulink/core/llvm/execution.py

Allows writeback of value of any compiled parameter

llvm/execution: Generalize parameter writeback function

---

tests/functions/test_distribution.py

Compiled fp32 tests have their own set of expected results, these should match with strictest tolerance.

tests/functions/distribution: Tighten tolerance for compiled results

---

broken_trans_deps.txt

https://github.com/onnx/onnx/issues/5202

deps: Add onnx==1.14.0 to broken_trans_deps

---

psyneulink/core/components/functions/stateful/memoryfunctions.py

clean up variable parsing and validation

ContentAddressableMemory

---

broken_trans_deps.txt

https://github.com/python-attrs/cattrs/issues/372

broken_trans_deps: Add cattrs==23.1.1 to broken deps list

---

psyneulink/core/globals/log.py

LogEntries: Do not store references to owner's owner

---

requirements.txt

Allow torch/modec_mdf dependency on aarch64/arm64

requirements: Update torch requirement from >=1.10.0,<2.1.0 to >=1.10.0,<2.2.0

---

psyneulink/core/components/functions/nonstateful/objectivefunctions.py
tests/functions/test_objective.py
tests/functions/test_stability.py

Convert Stability.normalize to FunctionParameter.

Functions/Stability: Convert 'normalize' to FunctionParameter

---

.github/workflows/pnl-ci.yml

ci/github-actions: Run the main CI job every day

---

psyneulink/core/components/functions/nonstateful/distributionfunctions.py
requirements.txt
tests/mechanisms/test_transfer_mechanism.py

PECOptimizationFunction requires scipy.
Restrict version to <1.12 to avoid failures in differential_evolution.

requirements: Add scipy to requirements file

---

broken_trans_deps.txt

https://github.com/beartype/beartype/issues/324

broken_trans_deps: Block beartype==0.17.1

---

conftest.py

The output format of show_config() changed, but the library now provides and option to return the values in a dictionary.

tests: Fix AVX512 detection on Numpy>=1.26

---

psyneulink/core/components/component.py
psyneulink/core/components/ports/parameterport.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/parameters.py
tests/misc/test_parameters.py

- speed optimizations for several Parameter and Parameters methods
- remove some strong circular references

Parameter-related fixes and optimizations

---

Scripts/Debug/Gilbert_Shallice_debugging_Interactive_activation
Scripts/Debug/Markus Stroop.py
Scripts/Debug/Umemoto_Feb2.py
Scripts/Debug/laura_test_no_noise_stroop_09_11_2018.py
Scripts/Examples/Gilbert_Shallice_Composition_Model.py
Scripts/Examples/Tutorial/Rumelhart Semantic Network (autodiff).py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/nonstateful/learningfunctions.py
psyneulink/core/components/functions/nonstateful/objectivefunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/mechanisms/modulatory/learning/learningmechanism.py
psyneulink/core/components/ports/modulatorysignals/learningsignal.py
psyneulink/core/components/ports/parameterport.py
psyneulink/core/components/projections/pathway/mappingprojection.py
psyneulink/core/globals/utilities.py
psyneulink/library/components/mechanisms/modulatory/learning/EMstoragemechanism.py
psyneulink/library/components/mechanisms/modulatory/learning/autoassociativelearningmechanism.py
psyneulink/library/components/mechanisms/modulatory/learning/kohonenlearningmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kohonenmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/components/projections/pathway/autoassociativeprojection.py
psyneulink/library/components/projections/pathway/maskedmappingprojection.py
setup.cfg
tests/control/test_gilzenrat.py
tests/mechanisms/test_processing_mechanism.py
tests/mechanisms/test_recurrent_transfer_mechanism.py

to fix `PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.`

Replace numpy matrix with numpy array

---

psyneulink/core/components/mechanisms/processing/transfermechanism.py

Do not hardcode the TimeScale value, it's available in compiled parameters.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2984

llvm, TransferFunction: Use compiled structures to determine the type of termination_measure

---

conftest.py
psyneulink/_typing.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py
psyneulink/core/components/projections/modulatory/controlprojection.py
psyneulink/core/components/projections/modulatory/gatingprojection.py
psyneulink/core/components/projections/modulatory/learningprojection.py
psyneulink/core/compositions/composition.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/compositionrunner.py
tests/functions/test_integrator.py

Prevent accidental modifications of globally instanced dicts.

tests: Use MappingProxyType to pass dict test parameters

---

psyneulink/core/scheduling/condition.py
psyneulink/core/scheduling/condition.pyi
tests/scheduling/test_condition.py

Dynamic generation of psyneulink equivalents of graph_scheduler `Condition`s hindered IDE analysis tools from providing class information, as shown in pycharm, for example:

Condition usability improvements

---

psyneulink/core/components/mechanisms/mechanism.py
tests/mechanisms/test_mechanisms.py

llvm/Mechanism: Reinit integrator_function in Mechanism reset if present

---

.github/workflows/pnl-ci.yml

ci/ga: Use console_output_style=count

---

psyneulink/core/globals/mdf.py
requirements.txt

 requirements: update pint requirement from <0.22.0 to <0.25.0

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py
tests/functions/test_transfer.py
tests/mechanisms/test_transfer_mechanism.py

Enable MAX_VAL and MAX_INDICATOR in compiled SoftMax function.

tests: Re-enable TransferFunction related tests

---

tests/mechanisms/test_transfer_mechanism.py

Use nullcontext for cases that do not emit warning. Add missing warning messages for cases that do.
Turn expected messages into regular expressions and pass them in "match" parameter to pytest.warns.

tests/TransferMechanism: Cleanup test_clip_with_respect_to_fct_bounds

---

psyneulink/library/compositions/autodiffcomposition.py

patch `AutodiffComposition.show_graph` with `jupyter`

add return value to show_graph

---

psyneulink/core/compositions/composition.py
tests/composition/test_composition.py

Composition: fix incorrect target parsing due to input order

---

Scripts/Examples/EVC OCM.py
requirements.txt

adjust code to relfect newest API

fixed EVC OCM

---

psyneulink/library/models/Botvinick_conflict_monitoring_model.py

This model was mentioned in the documentary but missing. 
Adapted a earlier version to the newest api.

Add Botvinick_conflict_monitoring_model to model folder

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
psyneulink/core/llvm/debug.py

Enable lint enforcing for basic rules.
Simplify Docs CI jobs.

ci/ga: Improve CI checks
