psyneulink/components/projections/modulatory/learningprojection.py

• LearningProjection
docstring rev (to include error_function)

• LearningProjection

---

psyneulink/components/component.py

- ROOD = ReadOnlyOrderedDict
- if you passed in function_params as an entry in params, this dictionary
would get assigned to object's function_params attribute, which could result
in coupling and unintended changes

Params: copy dict/ROODs nested in params arguments to avoid side effects

---

psyneulink/components/mechanisms/processing/objectivemechanism.py

• ObjectiveMechanism
_instantiate_input_states:
fixed bug in which (legacy) attempt was being made to instantiate defafult InputState locally --
should be left to be handled by InputState._instantiate_input_states.

fix to ObjectiveMechanism._instnatiate_input_states

---

psyneulink/components/functions/function.py
tests/functions/test_distance.py

Add test to make sure we return scalar
Fixes daebb626b4 ("Linear Combination Fix")

functions/DistanceFunction: Don't return vector for CROSS_ENTROPY metric

---

.travis.yml

Compiling from source takes time.
Download binary from python.org instead.
Do not autoupdate brew when installing graphviz
Saves 2-3mins on travis ci run

Improve travis macos environment

---

.idea/runConfigurations/Scratch_Pad.xml
.idea/runConfigurations/_RL_DDM.xml
psyneulink/components/mechanisms/mechanism.py
psyneulink/components/states/inputstate.py

• Mechanism
added external_input_values property  
returns values only of InputStates that are not marked as internal_only            
• InputState
added internal_only attribute
used to designate that input should not be required for this InputState
when owner Mechanism's role is EXTERNAL_INPUT

Feat/mechanism and input state/external internal

---

.travis.yml

This cashes just python packages. Caching homebrew did not lead to speed up.

travis: Add build cache configuration

---

.travis.yml

travis: Bump macos python 3.6 version to 3.6.6

---

.travis.yml

Hide sudo command on macos instances.
This should result in faster startup of linux instances.

.travis: Explicitly disable sudo

---

psyneulink/components/component.py
psyneulink/components/functions/function.py
tests/projections/test_projections.py

- Previously, matrix function parameter would be discarded because it was
not parsed from its string specification form
- Fixes #896

Component: if applicable, get matrix from parameter state when instantiating function

---

psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py

• OptimizationControlMechanism
- doctoring mods:  note re: distinction between objective_mechanism vs. evaluation_function
(assigned as objective_function of OptimizationFunction)

Docs/opt ctl mech/obj mech vs obj fct

---

dev_requirements.txt

dev_requirements: Restrict ipython to version 6.5.0

---

.travis.yml

Don't cache Travis provided files.
Drop python 3.7 deprecation warnings.

Travis enhancements

---

.travis.yml

Give up on containers. THey are going away:
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

travis: Switch to xenial for linux builds

---

.travis.yml

travis: Update macos python versions to 3.6.8 and 3.7.2

---

dev_requirements.txt

Reverts PrincetonUniversity/PsyNeuLink#1023
The tests take too long and timeout, need to investigate further.

Revert "dev_requirements: Allow pytest-4"

---

.appveyor.yml

Don't cache installed packages.
Restrict llvmlite to < 0.27
Restrict numpy to < 1.16

Appveyor fixes

---

.appveyor.yml

appveyor: Build all branches suffixed '-apy', or prefixed 'devel-'

---

.appveyor.yml

appveyor: Don't build 'devel-' prefixed branches

---

psyneulink/core/globals/utilities.py

This does not impact tests as pytest explicitly sets global seed to 0
before each test.

global/utilities: Default global seed to current time

---

.travis.yml

This should ease pressure on travis and allow PRs to start building
earlier.

travis: Restrict built branches.

---

psyneulink/core/globals/context.py
psyneulink/core/globals/log.py
requirements.txt

The functionality is available in core enum model since python 3.6.

Drop aenum module.

---

.travis.yml

macos10.6 was dropped with python3.5

travis, macos: Hardcode python macos version

---

dev_requirements.txt

- 1.28.0 now requires at least pytest 4
- pytest-profiling is currently incompatible with pytest 4,
but is introduced in https://github.com/manahl/pytest-plugins/pull/134

dev requirements: restrict pytest-xdist version

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/combinationfunctions.py
psyneulink/core/components/functions/interfacefunctions.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/selectionfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/states/parameterstate.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/builder_context.py

Get rid of _instance_defaults.
Try all granularities of compiled execution when `bin_execute=True`.
Add and use get_state_ptr helper function.
Stop using functools in Integrator function.

LLVM cleanups and refactoring

---

tests/composition/test_composition.py

Better readability.
pytest.marks and test naming work better.

tests/composition/test_compotisition_vector: Split parametrized arguments

---

tests/functions/test_combination.py
tests/llvm/test_multiple_executions.py

Properly mark llvm tests.
Don't instantiate llvm execution class in Python mode.

LLVM test cleanup

---

tests/functions/test_combination.py

tests/functions/linearcombination: Add missing llvm mark.

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/compositioninterfacemechanism.py
psyneulink/core/components/mechanisms/processing/integratormechanism.py
psyneulink/core/components/mechanisms/processing/objectivemechanism.py
psyneulink/core/components/mechanisms/processing/processingmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/states/state.py
psyneulink/core/components/system.py
psyneulink/core/globals/environment.py
psyneulink/core/globals/log.py
psyneulink/core/globals/parameters.py
psyneulink/core/globals/sampleiterator.py
psyneulink/core/globals/utilities.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/objective/comparatormechanism.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kohonenmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kwtamechanism.py
psyneulink/library/components/mechanisms/processing/transfer/lcamechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/compositions/autodiffcomposition.py

Direct import will stop working in python 3.8:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

treewide: Import collection ABCs from collection.abc module

---

.appveyor.yml

1.1.0 fails to import.
https://github.com/pytorch/pytorch/issues/21363

appveyor: Update pytorch package to version 1.0.1

---

.travis.yml

There is no such thing, and it disabled all caching.
https://github.com/travis-ci/travis-ci/issues/5876

travis: Drop apt cache

---

dev_requirements.txt

The issue with test enumeration was fixed in 4.6.1:
https://github.com/pytest-dev/pytest/issues/5358

requirements: Enable pytest >= 4.6

---

psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py

Uses of "self.history" within the Buffer function are not correct, because history is a Parameter. This causes the Buffer's actual deque buffer to grow without limit, causing progressive slowdown in the StabilityFlexibility model.
This was only evidenced by commit a26b30ab7, which correctly set .most_recent_execution_id on Functions; before, the incorrect non-stateful version was coincidentally working.

Fix Buffer function not being properly stateful

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/parameterinterfacemechanism.py
psyneulink/core/components/projections/modulatory/controlprojection.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/keywords.py
tests/composition/test_control.py

Created new Mechanism: ParameterInterfaceMechanism. It is a subclass of CompositionInterfaceMechanism that is granted special permissions to use ControlSignals as its OutputStates.
Compositions now instantiate with a ParameterInterfaceMechanism attribute.
Implemented feature allowing OCM of a composition to modulate parameter states of nested nodes via ParameterInterfaceMechanism. Necessary Projections, InputStates, and ControlSignals are added to compositions in _create_CIM_states().
Added _get_nested_nodes() and _get_nested_compositions() convenience methods to Composition.

feature: OCM modulation of nested node parameters

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/learningfunctions.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/mechanisms/adaptive/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/integratormechanism.py
psyneulink/core/components/process.py
psyneulink/core/components/projections/modulatory/controlprojection.py
psyneulink/core/components/projections/projection.py
psyneulink/core/components/states/outputstate.py
psyneulink/core/components/states/state.py
psyneulink/core/components/system.py
psyneulink/core/compositions/composition.py
psyneulink/core/compositions/compositionfunctionapproximator.py
psyneulink/core/globals/context.py
psyneulink/core/globals/preferences/componentpreferenceset.py
psyneulink/library/components/mechanisms/adaptive/control/evc/evcauxiliary.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/compositions/gymforagercfa.py
psyneulink/library/compositions/regressioncfa.py
setup.cfg

Fix and enable few docstring style guidelines. These were followed in most places and needed only a few changes;
D201	No blank lines allowed before function docstring
D209	Multi-line docstring closing quotes should be on a separate line
D210	No whitespaces allowed surrounding docstring text
D211	No blank lines allowed before class docstring

Travis docstrings avy

---

.appveyor.yml

pytorch 1.2 works ok on windows with numpy <1.16.
Use ARCH env var to decide if pytorch is avialable.

appveyor: Remove pytorch version restriction

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/compositions/composition.py
tests/composition/test_control.py
tests/mechanisms/test_control_mechanisms.py

function:
-Corrected non-stateful use of modulation parameter
-Corrected non-stateful use of initialization_status parameter
composition:
-Previously, nested compositions executing within simulations would rely on their input projections to provide values to the input states of their input CIMs. Under the circumstance that a nested composition itself had an OCM and was executing within its own simulation, the projected value was invalid because the afferent node had not executed in that execution id. To fix this issue, Compositions executing within simulations now have their input values assigned to them under all circumstances.
-When validating input to be assigned to input_CIMs, uses default value instead of current value to find shape that must be matched by input. Using current value …

Bug Fixes for PCIM Functionality

---

.travis.yml

travis: Run pytest directly instead of as python module

---

psyneulink/core/components/mechanisms/mechanism.py

Fix typo making the list include input mod_afferents twice.

mechanism: List output state mod_afferrents in mechanism's list.

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
tests/functions/test_memory.py

Previously, class default values of Parameters could be inadvertently shared among instances of the class

Component: ensure default Parameter values are not shared

---

tests/composition/test_autodiffcomposition.py

Fixes failures with no pytorch installed.

test, autodiff: Mark batching tests as 'pytorch'

---

psyneulink/library/compositions/compiledoptimizer.py
psyneulink/library/compositions/pytorchmodelcreator.py

This drastically reduces compilation time, as Loop-invariant code motion optimization from the compiler was over-eager to try and optimize the line.

Move `compiledoptimizer.zero_grad` to a explicitly called llvm function.

---

psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py

D210: No whitespaces allowed surrounding docstring text

codestyle: Fix D210

---

.travis.yml

travis: Use Ubuntu's native python instead of travis'

---

.travis.yml

travis: Bump python 3.7 version to 3.7.5

---

.appveyor.yml

appveyor: Restrict pywin32 to <226 to work around appveyor issue

---

.travis.yml

travis: Rename 'matrix' -> 'jobs'

---

psyneulink/core/globals/utilities.py
tests/misc/test_user_seed.py

Convert to ms before casting to integer.
Fixes random seed initialization on macos.

utilities: Use time since epoch to initialize the random seed

---

psyneulink/core/components/ports/modulatorysignals/modulatorysignal.py

Previously, if a ModulatorySignal was named the same as one of its receiver's efferents, it would be considered not a default name and not assigned using the normal naming pattern

Use standard renaming for ModulatorySignals corresponding to an efferent

---

psyneulink/core/components/component.py
psyneulink/core/globals/parameters.py

The `spec` attribute on `Parameter` is the actual object or value that was passed in to a Component constructor, when that value was automatically parsed. This occurs for example for tuple specifications of input_ports or modulable parameters, and is used to save the original specification for future reference

Parameter: add and set spec attribute

---

docs/source/Parameters.rst
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/globals/parameters.py

Previously, to do simple type checking for Parameter values, you needed to use the generic function validation pattern. 
Now, simply add a tuple of types as the `valid_types` argument to a Parameter.

Refactor Parameter type validation

---

psyneulink/core/llvm/builtins.py
tests/llvm/test_helpers.py

It should work on windows as well if the c runtime library can be identified.
Add test.

add supoprt for printf in compiled code on macos

---

tests/misc/test_user_seed.py

tests/user_seed: Use sys.executable instead of 'python'

---

.travis.yml

travis: Bump python version to 3.8.1 and 3.7.6

---

dev_requirements.txt
tutorial_requirements.txt

This reverts commit 012c8d5130141a4db41d173d7f9ef1073f7a5bda.
Backwards compatibility was fixed in 5.0.1

Revert "{dev,tutorial}_requirements: Restrict nbformat to 4.x"

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/combinationfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/mechanisms/mechanism.py

- Mechanisms called _handle_default_variable in Mechanism.__init__, and then again in Component.__init__. This is replaced by a single call in Component.__init__
- All default Parameter values are available for _handle_default_variable in a subclass
- Correctly set `parameters.variable._user_specified` universally, so previous overrides doing this are unnecessary

Condense calls to and overrides of _handle_default_variable

---

psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/llvm/test_helpers.py

@jvesely 
This pull fixes compiled printf by reverting it to the original version, and also adds extra test cases to better check for correctness.
There is a bug with the live version in which varargs are not correctly passed to the builtin printf wrapper

Fix compiled printf

---

psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/helpers.py
psyneulink/library/compositions/compiledloss.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/composition/test_autodiffcomposition.py

When the MSE Loss function was previously changed, the compiled version still used the old one.
These changes fix that issue, and re-enable correctness tests for compiled autodiff correctness
Additionally, there are some cleanups made to compiled print statements that allow for clearer debugging

Fix MSE Loss function

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/port.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/builder_context.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
setup.cfg
tests/functions/test_integrator.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_lca.py

Used by `LCAMechanism`
Add support for `LeakyCompetingIntegrator` function, used by `LCAMechanism`.
Enable compilation tests for `LCAMechanism`.
Cleanup code generation for mechanisms, reuse standard functions for generating parameter and state structures.

llvm: Implement support for compiling mechanisms using "execute_until_finished"

---

psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_learning.py

This change removes the stored 'bias' term from `pytorchmodelcreator.py`, and also refactors `autodiffcomposition.get_parameters` to only return weights.
This was done because the stored bias in `pytorchmodelcreator.py` was always being set to zero, meaning it did not have an impact on the models.

autodiff: Remove unused internal `bias` term (#1461)

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/combinationfunctions.py
psyneulink/core/components/functions/distributionfunctions.py
psyneulink/core/components/functions/interfacefunctions.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/selectionfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/port.py
psyneulink/core/components/projections/projection.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/compiledloss.py
psyneulink/library/compositions/compiledoptimizer.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/composition/test_autodiffcomposition.py
tests/states/test_output_states.py

Rework caching of generated functions based on tags.
Switch 'learning' code generation based on tag rather than PNL parameter.
Enable switching of 'learning_enabled' in nested learning tests
Add support for OWNER_EXECUTION_COUNT output port specification.

llvm: Add tags to allow multiple function variants based on one object.

---

requirements.txt

requirements: restrict torch to x86_64 and CPython

---

.github/workflows/pnl-ci.yml

Switch back to using github/actions.
Generate junit XML tests summary.

github-actions: Upload test results and built artifacts

---

psyneulink/core/components/mechanisms/mechanism.py
tests/mechanisms/test_recurrent_transfer_mechanism.py

Leave is_finished_flag at False when in one-shot mode.
The executions that reached max_iterations_before_finished are finished.

mechanism: Count the number of completed iterations in num_executions_before_finished

---

psyneulink/library/compositions/autodiffcomposition.py

param_init_from_pnl's functionality will be fully replaced in an upcoming refactor. Since some functionality was changed with respect to biases, a warning was added to explicitly notify users who may have been relying on its functionality.

autodiff: Add doc deprecating Autodiffcomposition.param_init_from_pnl

---

.travis.yml

travis: Bump mac os python to 3.8.2

---

.github/workflows/pnl-ci.yml

github-actions: Do not try to upload test results if the job was canceled

---

.travis.yml

travis: Bump macos python 3.7 to 3.7.7

---

.github/workflows/pnl-ci.yml

github-actions: Upload test results artifacts on both success and failure

---

psyneulink/core/llvm/helpers.py

Fixes an issue where `ctypes.util` silently failed.
See (https://github.com/qpit/thorlabs_apt/issues/11) for more information.

llvm: Fix ctypes import error in printf

---

README.rst

README: Use GitHub Actions CI badge instead of Travis

---

psyneulink/core/llvm/jit_engine.py

This helps compilation times and has little impact on performance.

llvm/jit: Temporarily disable compiler optimizations.

---

.appveyor.yml

These builds are redundant and just increase CI load.

appveyor: Do not build branches with open PRs

---

.appveyor.yml

This allows pip to build local wheels of sdist packages

appveyor: Install wheel

---

.travis.yml

This allows pip to build local wheels of sdist packages.

travis: Install wheel

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
setup.cfg
tests/composition/test_control.py

Fix parsing of 'evaluate' inputs into simulation inputs.
Drop 'costs' parameter, it can have an invalid shape.

llvm: Fix controller compiled shape mismatch

---

psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/composition/test_control.py

Fixes an issue where if there was only one modulatory input to a RTM, compilation would fail.

llvm: (Fix) Add mod. inputs to input_type_list if len is >= 1

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/compositioninterfacemechanism.py
psyneulink/core/compositions/composition.py
tests/composition/test_interfaces.py

Reworked previously reverted warning that occurs when a user manually adds a Port to a CIM

CompositionInterfaceMechanism/add_ports: emit warning when user manually adds Port to CIM

---

psyneulink/core/components/functions/distributionfunctions.py
tests/functions/test_distribution.py

As originally intended.
Add test.

llvm, functions/DriftDiffusionAnalytical: Use abs value to check magnitude

---

psyneulink/core/components/projections/pathway/mappingprojection.py
tests/composition/test_interfaces.py
tests/projections/test_projection_specifications.py

To prevent unnecessary warnings, check that parameter is a string before doing comparison with keyword

Fix/string comparison operator/check if string first

---

psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/selectionfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/functions/transferfunctions.py
tests/mechanisms/test_ddm_mechanism.py

It should not be reset during reinitialize.
The runtime compiler does not rely on this list anymore either.

components: Drop 'random_state' from 'stateful_attributes'

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/codegen.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/composition/test_learning.py

Add and use 'value' stateful param.
move 'is_finished' to TransferMechanism.
Drop unnecessary input struct workarounds.

llvm: Cleanup and simplify RecurrentTransferMechanism

---

psyneulink/core/components/ports/port.py

llvm, Port: Check that the input struct type matches the number of incoming projections

---

psyneulink/core/compositions/composition.py
psyneulink/core/llvm/execution.py
tests/composition/test_composition.py

Reenable node-compiled execution of nested compositions if there are no modulatory projections.
Add support for generalized generator inputs.

llvm: Switch to Composition provided input parsing routine

---

psyneulink/library/compositions/autodiffcomposition.py

If torch is available, importing pytorchmodelcreator should succeed.

autodiffcomposition: Do not hide pytorchmodelcreator import in a try block

---

.travis.yml

'cache: pip' seems to only work with 'language: python'

travis: List pip cache location explicitly

---

psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/execution.py
psyneulink/library/compositions/pytorchmodelcreator.py

Drop 'alwaysinline' attribute.
Use cached property instead of generating the list of compiled params.
Use a structural check instead of python param value.

llvm: fixes

---

psyneulink/core/compositions/composition.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_composition.py
tests/mechanisms/test_ddm_mechanism.py

This pull adds:
- A compiled `WhenFinished` condition
- A compiled `is_finished` condition for DDMs
- A bugfix for pass counting in the compiled scheduler
- Tests for scheduler conditions implemented in both Python and compiled (and some differences discovered between Python and compiled runs of certain conditions)
Fixes #1509.

Compiled `WhenFinished` Condition

---

psyneulink/__init__.py
setup.cfg

This allows it to be cleared after every test, avoiding memory leak.
Fixes failing CI due to OOM condition.
Allow parallel test runs by default.

Add pathway registry to the list of primary_registries

---

psyneulink/library/compositions/compositionrunner.py
tests/api/test_api.py

This pull fixes a typo in `composition.learn`, which caused too many results to be returned when learning with minibatch sizes greater than 1.

Fix results shape from learning

---

.github/workflows/pnl-ci.yml

github-actions: Don't use fail-fast strategy.

---

psyneulink/core/globals/parameters.py

This removes the need for most getattr calls using caching. 
If a `Parameter` is marked as `_inherited=True`, then it does not store its default value (for example) explicitly but rather inherits the value in real time from its closest non-inherited parent. This was implemented by deletion of the attribute and repeated getattr calls to find the correct inherited value. 
This branch implements storage of a reference to the closest uninherited parent, which is recalculated lazily in the uncommon event that the correct parent is changed (by explicitly setting the default value for a previously inherited parent, or by calling `Parameter.reset()` on an uninherited parent in some cases).  
It also removes most getattr calls for `Parameters`, which now mostly only occurrs when setting up …

Optimize Parameter inheritance

---

tests/composition/test_autodiffcomposition.py

Increase number of training epochs to fix '1 xor 1' result.
Codestyle.

tests/xor_training_correctness: Test all results against target

---

psyneulink/core/compositions/composition.py
tests/composition/test_interfaces.py

Fixed issue causing projections that were invalidated by PCIM routing not to be deleted

Delete projections made redundant by PCIM routing

---

psyneulink/core/compositions/composition.py
psyneulink/core/globals/context.py
psyneulink/core/globals/log.py
psyneulink/library/components/mechanisms/modulatory/learning/kohonenlearningmechanism.py

- SIMULATION is now renamed to SIMULATION_MODE
- Context.execution_phase can now only have one flag
- Context.runmode can now have two flags only if SIMULATION is one of them
- calls to `add_flag` for Context.execution_phase are replaced with simple attribute setting

Context: Change SIMULATION from an execution_phase to a runmode

---

psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/projections/modulatory/gatingprojection.py
psyneulink/library/components/mechanisms/processing/objective/comparatormechanism.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py

`Parameter._user_specified` is meant to indicate whether the caller provided a value for a Parameter when constructing a Component. If a value other than None is used as a default value for an argument in __init__, `_user_specified` will always be True

Fix user_specified for several Parameters

---

psyneulink/core/components/mechanisms/processing/processingmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/outputport.py

Fixes bug where every OutputPort created from a given standard_output_ports template would share one Function instance.

OutputPort: do not share Function instances in standard_output_ports

---

.travis.yml

travis: Bump llvm version to 9

---

tests/composition/test_composition.py

The two tested lines trigger 2 warnings which are captured in undefined
ordered.
It's the second line that triggers the warning were interested in so
move the first line out of the capture block.
Split 'and' in asserts while at it.

tests: Remove warning ambiguity in TestDuplicatePathwayWarnings

---

psyneulink/core/compositions/composition.py

composition: fix indexing typo when comparing to 'role'

---

psyneulink/core/compositions/composition.py
tests/composition/test_composition.py

`NodeRole.CONTROLLER` is assigned as a special case if a Composition has a controller. The controller is not in `Composition.nodes` and has no other roles.

Add NodeRole.CONTROLLER for Composition.controller

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/combinationfunctions.py
psyneulink/core/components/functions/distributionfunctions.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/interfacefunctions.py
psyneulink/core/components/functions/learningfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/modulatory/learning/learningmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/inputport.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/ports/port.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/utilities.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/integrator/episodicmemorymechanism.py
setup.cfg
tests/functions/test_combination.py
tests/functions/test_memory.py
tests/log/test_log.py
tests/mechanisms/test_input_state_spec.py
tests/mechanisms/test_kwta.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/misc/test_utilities.py

Handle numpy.VisibleDeprecationWarning and future ValueError produced by creating a numpy.ndarray with elements of varying shape or type, which was introduced by https://github.com/numpy/numpy/pull/15119
https://numpy.org/neps/nep-0034-infer-dtype-is-object.html

Fix numpy 1.19 deprecations

---

psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/execution.py
tests/composition/test_control.py
tests/llvm/test_builtins_random.py
tests/mechanisms/test_control_mechanism.py
tests/models/test_bi_percepts.py
tests/models/test_greedy_agent.py

Drop references to per node PTX mode.
Fix builtin random tests failures since configurable cuda grid block size.
Improve generation of input structures.

llvm/cuda: Cleanup

---

Scripts/Debug/Yotam LCA Model.py
Scripts/Examples/Tutorial/Rumelhart Semantic Network (autodiff).py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/execution.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/compiledloss.py
psyneulink/library/compositions/compiledoptimizer.py
psyneulink/library/compositions/pytorchcomponents.py
psyneulink/library/compositions/pytorchllvmhelper.py
psyneulink/library/compositions/pytorchmodelcreator.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_learning.py
tests/functions/test_transfer.py

- Fix correctness issues in learning (now should be numerically exact)
- Reorder operations in the ADAM optimizer to conform to the exact ordering used in PyTorch
- Cleanup compiled learning code + setup for compiled RNN
- Add additional tests for autodiff correctness
- Remove autodiff.get_parameters (obsoleted by the ability to get matrices directly from the projections)

Fix learning correctness

---

psyneulink/core/globals/parameters.py
tests/misc/test_parameters.py

Previously, a ParameterAlias would become a new Parameter copy of its source when deepcopied

ParameterAlias: ensure ParameterAlias returned when copied

---

psyneulink/core/components/functions/optimizationfunctions.py

Remove link at top of `optimizationfunctions` module docstring for `ParamEstimationFunction`, which is currently hidden because it is still in development

Remove inactive link from docs

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/ports/port.py
psyneulink/core/llvm/builder_context.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py

Compose the structures recursively to make better use of caches. This reduces the number of Python -> LLVM conversions by ~40%.
Compose initializers recursively, this should help reduce initialization time and memory usage.
Use LLVM integer types for numpy.integer dtype.

llvm: Refactor param/state struct generation

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/ports/port.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py

Convert allocation cost computation to OutputPort variant

llvm: Use standard param/state structures for Ports and GridSearch

---

psyneulink/core/compositions/composition.py

Enumeration of any-length cycles and brute-force computation of strongly
connected components caused unusable slow down in highly connected graphs.
Replace with networkx calculation of strongly connected components, simplified
iteration over potentially prunable edges, and short-circuits.
Rename:
Composition.get_cycles -> Composition.get_strongly_connected_components

Graph: make prune_feedback_edges faster

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/components/ports/parameterport.py
psyneulink/core/globals/parameters.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kohonenmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/lcamechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/components/projections/pathway/autoassociativeprojection.py
tests/misc/test_parameters.py

parameters: add FunctionParameter and SharedParameter subclasses
- serve as a reference to a Parameter on one of the Component's attributes or
other Parameters
- values are shared between target Parameter and SharedParameter
- when included in constructor, automatically passed on instantiation to
relevant secondary Functions
- other objects (e.g. RecurrentTransferMechanism.learning_mechanism) must still manually retrieve these parameter values as before

Add FunctionParameter and SharedParameter subclasses

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/gating/gatingmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/modulatory/learning/learningmechanism.py
psyneulink/core/components/mechanisms/processing/objectivemechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/inputport.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/ports/port.py
psyneulink/core/components/projections/modulatory/learningprojection.py
psyneulink/core/components/projections/pathway/mappingprojection.py
psyneulink/core/llvm/execution.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/modulatory/learning/autoassociativelearningmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kohonenmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py

Dot notation may work coincidentally, but may subtly return values for the wrong context. `defaults` or `get`/`_get` should be used instead.

Remove internal use of dot notation for stateful parameters

---

psyneulink/core/components/functions/objectivefunctions.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/llvm/execution.py
tests/functions/test_distance.py
tests/functions/test_stability.py
tests/llvm/test_helpers.py
tests/mechanisms/test_processing_mechanism.py

Make code generation float precision agnostic.
The switch between fp64 and fp32 is not exposed because there's still large number of tests that fail.
Some tests fail because of reduced precision, others fail because they don't use `Execution` classes and don't implement input conversion.

llvm: Convert input types when invoking compiled functions

---

tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_lca.py

parameters are configured in a way that LCA == DDM followed by Logistic

tests: Add DDM/LCA equivalence tests

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/jit_engine.py
tests/llvm/test_custom_func.py
tests/mechanisms/test_processing_mechanism.py

Make IR generation for execution counts bitwidth agnostic.
Add minor CUDA tune ups.

llvm: Support more integer widths

---

.travis.yml

workaround for: https://github.com/pytest-dev/pytest-xdist/issues/602

travis: Use nproc to get the number of CPU cores instead of pytest-xdist 'auto'

---

psyneulink/core/llvm/codegen.py

llvm: Do not reuse node function name for node invocation wrapper

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/globals/parameters.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kwtamechanism.py
psyneulink/library/components/mechanisms/processing/transfer/lcamechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
psyneulink/library/components/projections/pathway/autoassociativeprojection.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/misc/test_parameters.py

- add `dependencies` field to `Parameter`, which is one or a set of Parameter names of secondary Functions which must be instantiated before the current Parameter (ex: `RecurrentTransferMechanism.combination_function` must be instantiated before `RecurrentTransferMechanism.integrator_function`)
`default_variable` is now immediately specified on creation of secondary functions to identify and resolve conflicts with initializers and any other parameters
`default_variable` of secondary Functions' secondary Functions are also set correctly on instantiation and when updated with `_update_default_variable`
Compared to devel, these tests changed as a result of the following numbers of calls to the `random_state` parameter of noise functions during initialization:
| Test Name | random_state …

Simplify, improve instantiation of secondary Functions

---

psyneulink/core/llvm/execution.py
psyneulink/library/compositions/compositionrunner.py

Previously using generators would automatically imply the number of runs == number of inputs.
Using fewer generator inputs than runs allows learning to provide only single epoch data if the input order does not need to be randomized.

llvm/autodiff: Allow more runs than generated inputs

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/learningfunctions.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/objectivemechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/port.py
psyneulink/core/compositions/composition.py
psyneulink/core/compositions/showgraph.py
psyneulink/core/globals/context.py
psyneulink/core/scheduling/scheduler.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/objective/comparatormechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/composition/test_composition.py
tests/log/test_rpc.py
tests/mechanisms/test_integrator_mechanism.py

- Solves an issue where manually creating a Context object could cause unintended use of the None or a default context.
- Adds arguments `fallback_default` and `fallback_most_recent` to the `handle_external_context` decorator that can be used to determine whether the function should use an object's `default_execution_id` or `most_recent_context.execution_id` if context is unspecified

Context: generate an execution_id on creation if unspecified

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/debug.py
psyneulink/core/llvm/execution.py
psyneulink/library/compositions/autodiffcomposition.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/models/test_greedy_agent.py

Add option to print ctype structure sizes.
Remove duplicate structures from Autodiff composition.
Use np.dim() == 0 instead of np.scalar() to detect dimensionality change of modulated parameters.

llvm: Struct generation fixes

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/learningfunctions.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/parameters.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/composition/test_composition.py
tests/mechanisms/test_mechanisms.py

- Add `initializer` flag to `Parameter` that when specified as the name of another Parameter identifies it as a `stateful_attribute` (resettable)
- Accept keyword arguments for `Component.reset`

Determine resettable attributes from Parameters

---

.github/workflows/pnl-ci.yml
.travis.yml
leabra_requirements.txt
setup.py

Reverts PrincetonUniversity/PsyNeuLink#1815
#1815 broke pypi compatibility by including `leabra` as a direct dependency
See [here](https://github.com/benureau/leabra/issues/7) for more information

Revert "deps: Convert leabra to 'extra' dependency"

---

conftest.py
psyneulink/__init__.py
psyneulink/library/models/Cohen_Huston1994.py
psyneulink/library/models/Cohen_Huston1994_horse_race.py
psyneulink/library/models/GilzenratModel.py
psyneulink/library/models/Kalanthroff_PCTC_2018.py
psyneulink/library/models/MontagueDayanSejnowski96.py
psyneulink/library/models/Nieuwenhuis2005Model.py
tests/models/test_documentation_models.py

matplotlib figures block execution normally; disable this in all documentation models in `psyneulink/library/models/` when running pytest

library models: generate figures during testing

---

.github/workflows/pnl-ci.yml

The new cmake built version has problems with locations of executables:
https://chocolatey.org/packages/Graphviz/2.44.1

github-actions: Restrict graphviz version on windows

---

psyneulink/core/components/__init__.py
psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/functions/transferfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/gating/gatingmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/modulatory/learning/learningmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/inputport.py
psyneulink/core/components/ports/modulatorysignals/learningsignal.py
psyneulink/core/components/ports/modulatorysignals/modulatorysignal.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/ports/port.py
psyneulink/core/components/projections/projection.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/context.py
psyneulink/core/globals/parameters.py
psyneulink/core/globals/preferences/preferenceset.py
psyneulink/core/globals/registry.py
psyneulink/library/components/mechanisms/processing/objective/comparatormechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kohonenmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/mechanisms/test_transfer_mechanism.py

- Reduce the number of individual places in which new Context objects are manually created or modified to affect execution
- Remove or condense several `ContextFlags` where similar in intent or behavior:
- `ContextFlags.COMPONENT` -> `ContextFlags.CONSTRUCTOR`
- `ContextFlags.PROPERTY`
- `ContextFlags.INSTANTIATE` in favor of `is_initializing`
Compared to devel, these tests changed as a result of the following
numbers of calls to the random_state parameter of noise functions during
initialization:
| Test Name | random_state Parameter RNG method | offset |
| - | - | - |
test_transfer_mech_array_var_normal_len_1_noise | random_state.normal | -4
test_transfer_mech_normal_noise | random_state.normal | -4
test_transfer_mech_exponential_noise | random_state.random | -4 …

Simplify Context

---

.travis.yml

numpy and scipy now provide aarch64 wheels, the rest should build within
travis' time limit.

travis: Drop precache stage.

---

requirements.txt

Not sure why dependabot didn't pick this one up.
1.7.1 includes python3.9 wheels

requirements: Bump pytorch to 1.7.x

---

.travis.yml

Prevents unbounded growth of pip's http cache.

travis: Restrict cache to built wheels

---

.travis.yml

This works around a problem in handling dependencies when building Python modules.
https://github.com/pypa/pip/issues/9239

travis: Explicitly install numpy ahead of other dependencies

---

psyneulink/core/compositions/composition.py
psyneulink/core/globals/json.py
psyneulink/core/scheduling/scheduler.py

- "conditions" entry moved from graph["parameters"]["schedulers"][\<execution phase>]["conditions"] to graph["conditions"]
- Compositions now have only one scheduler, for any execution phase, so execution phase entry was obsolete. other change is for spec redefinition
- uses of TimeScale in termination conditions dict replaced with string name of the scale
- ["conditions"]["node"] renamed to ["conditions"]["node_specific"]

Update JSON/MDF format to latest spec

---

psyneulink/core/llvm/helpers.py

llvm/helpers: Simplify array loop id to avoid illegal characters

---

psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/globals/utilities.py

Require user to instantiate psyneulink noise function types in a list because we can't infer their intended variable shapes

StatefulFunction: validate for uninitialized noise functions in list 

---

.github/workflows/pnl-ci.yml
.github/workflows/pnl-docs.yml

Don't run full CI on documentation only changes.
Adds a script that generates 'before' and 'after' html documentation and posts diff as a comment.
Comment posting works only on PRs within one repo (should cover dependabot requests)

Add CI script checking differences in generated documentation

---

psyneulink/core/components/component.py
tests/misc/test_parameters.py

When passing a Component as a shared parameter, it will be copied to set a default value for the shared parameter so any changes are decoupled from the original. This resulted in warnings designed for the situation in which a user assigned different values for a parameter and its shared parameter, despite the user only assigning one.

Component: fix incorrect warning for shared parameter conflict

---

.github/actions/cleanup-pip-cache/action.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

Doesn't work on python 3.8/3.9 see #1870 .
There's a lot of duplicated code, but unfortunately, GitHub actions do not allow for easy templates/sharing

Add CI jobs to build documentation

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
tests/functions/test_accumulator_integrator.py
tests/functions/test_buffer.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_transfer_mechanism.py

`_try_execute_param`, which generates noise values from functions, is moved to Component and now supports variables of any length or dimension. Noise may be specified with the same flexibility and is applied elementwise, as in the `i`th element of noise will be executed (if a function) and applied to the `i`th element of variable, including any deeper dimension. For example, with a noise specification of `[pnl.NormalDist(), pnl.UniformDist()]` and a variable of `[[a, b], [c]]`, normal noise will be individually applied to elements `a` and `b` and uniform noise to `c`. 
There are two convenience exceptions:
1. if the variable shape is the same as the noise shape except with extra wrapping dimensions, the noise will be applied to the deepest dimension of variable (e.g. variable `[[[[a, …

Consolidate and generalize noise value generation

---

.github/workflows/pnl-ci-docs.yml

This deployment script assumes that the documentation is in `gh-pages` branch.
`master`, `devel`, and `docs` have their documentation in their respective subfolder (e.g. [0], [1])
Other branches still build the documentation but skip the deployment job (e.g. [2]).
Tags are deployed in the documentation root dir, but only if they exist on the master branch. (e.g [3]).
Tags on other branches skip the deployment job (e.g. [4])
[0] https://github.com/jvesely/PsyNeuLink/actions/runs/499816341
[1] https://github.com/jvesely/PsyNeuLink/actions/runs/499820392
[2] https://github.com/jvesely/PsyNeuLink/actions/runs/499868143
[3] https://github.com/jvesely/PsyNeuLink/actions/runs/499818119
[4] https://github.com/jvesely/PsyNeuLink/actions/runs/499821025

github-actions: Add documentation deploy jobs for branches and tags

---

Scripts/Examples/LC Control Mechanism Composition.py
psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/modulatory/learning/learningmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/inputport.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/projections/projection.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/models/Nieuwenhuis2005Model.py
tests/composition/test_composition.py
tests/control/test_gilzenrat.py

Parameter dot-notation used `Parameter._set`, which allowed users to change read-only parameters with no warning and skip parsing. Dot notation now uses `set` to require explicit use of `.set` with `override=True` to bypass read-only restrictions.

Fix dot-notation bypass of read-only parameter warning, parsing

---

psyneulink/core/components/component.py
tests/mechanisms/test_mechanisms.py

Instead of assuming any Component other than a DistributionFunction is part of a modulatory specification, parse only ModulatoryMechanism_Base, ModulatorySignal, ModulatoryProjection_Base. 
Corrects problem where noise functions other than DistributionFunctions would not run during execution unless set after initialization of the owning Component.

Fix overeager modulatory specification parsing

---

docs/source/Preferences.rst
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/globals/preferences/basepreferenceset.py

`reportOutputPref = True` prints only input/output for mechanism execution
`reportOutputPref = 'params'` or `'parameters'` prints values of parameters as well (fix printing of full Parameter class)

Mechanism: slim reportOutputPref printing, add option

---

psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py
psyneulink/core/scheduling/condition.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_composition.py

Drop `EveryNCalls` scheduling condition. The implementation was incorrect and unused.
Fix reset of PASS scale execution counts.
Add TimeScale parameter to {At,After,Before}NCalls scheduling conditions.
Regresses: https://github.com/PrincetonUniversity/PsyNeuLink/issues/1580

llvm: Rework scheduler to make use of stored execution counts

---

psyneulink/core/scheduling/scheduler.py
tests/scheduling/test_scheduler.py

condition incorrectly depended on the execution of all nodes in the previous consideration set, instead of its structural parents

fix(scheduler): default condition dependencies

---

psyneulink/core/llvm/helpers.py
tests/scheduling/test_scheduler.py

We can match the semantics in N=1 special case.
This is needed to support autogenerated conditions for nodes that don't have any.
Fixes Python-PTX execution mode since dac19d4fb6df901dd1a020c38d1c40253997e517 ("llvm/scheduler: Remove 'EveryNCalls' scheduling condition")
Partially reverts dac19d4fb6df901dd1a020c38d1c40253997e517 ("llvm/scheduler: Remove 'EveryNCalls' scheduling condition")

llvm/scheduler: Restore and reimplement 'EveryNCalls' scheduling condition

---

.github/workflows/pnl-ci.yml

github-actions: Restrict tests to 80 mins

---

.github/dependabot.yml

dependabot: Allow up to 15 open pull requests for pip packages

---

psyneulink/core/components/component.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/execution.py
setup.cfg
tests/functions/test_distance.py
tests/functions/test_transfer.py
tests/llvm/test_helpers.py

Provide factory interface for generating single context executions.
Store composition executions as param composition param for both CPU and GPU

llvm: Move generated binary structures from parameters to execution

---

psyneulink/core/llvm/execution.py
tests/llvm/test_debug_composition.py

Add 'stat' to the test of debugging flags.
Fixes: fd5a419271c73cc327d0f6ef6b1e6c8eee4e9f1f ("llvm/execution: Store binary buffer of scheduler structures locally")

llvm/execution: Use correct type to print scheduler conditions structure stats

---

psyneulink/core/components/component.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/llvm/execution.py
psyneulink/library/compositions/pytorchcomponents.py

The values are already in their original locations.

llvm: Stop using SharedParams in compiled code

---

psyneulink/__init__.py
requirements.txt

Rich does not detect it is running in a jupyter notebook on Google colab. This is a bug in rich for which I have made a pull request.
See [here](https://github.com/willmcgugan/rich/pull/1085). Until this is accepted I suggest we just monkey patch rich.console._is_jupyter. If the pull request is accepted then this can be reverted.

Fix jupyter detection for rich while running on colab

---

conftest.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/scheduling/test_scheduler.py

This changes the order of generated tests slightly.

tests: Add fixture for compiled composition tests that don't support per-node compiled execution

---

psyneulink/core/components/functions/optimizationfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py
psyneulink/core/llvm/helpers.py
tests/composition/test_control.py
tests/models/test_greedy_agent.py

Generate samples locally instead of preparing the entire array in Python.
Add evaluate range wrapper.
Split the total number of evaluations evenly across all cores.

llvm: Implement multihreaded parallel evaluate

---

psyneulink/core/globals/preferences/basepreferenceset.py
psyneulink/core/globals/preferences/preferenceset.py
tests/composition/test_report.py

- add tests to ensure `'params'` option does not break again
- add workaround to Preference validation to mimic pre- 8c0eecc2c674a481138420f703ee661d39239052 behavior (4460fe5ea499441d8f0a255b62c4840de9c2b568)

Reenable reportOutputPref 'params' option

---

psyneulink/core/components/functions/statefulfunctions/integratorfunctions.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_composition.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_mechanisms.py
tests/scheduling/test_scheduler.py

Fixes the specific case from #1878 but not in general. DriftDiffusionIntegrator and any owning mechanism now produces 2d value. Removes automatic 2d-cast of previous_value.

DriftDiffusionIntegrator: avoid always producing 3d value

---

psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
tests/composition/test_control.py

Make generated simulation execution_ids more verbose and unique, ensuring no
simulations reuse state.
If a Composition and one of its nested Compositions both run simulations,
execution ids may be inadvertently reused. See test_input_type_equivalence for
an example.
By default the outer Composition 'ocomp' runs with execution_id 'ocomp'. When it
simulates first, the generated execution_id will be 'ocomp-sim-0'. The inner
Composition 'icomp' will run during this simulation. Later, during
non-simulation running of ocomp, icomp will run under execution_id 'ocomp' and
simulate itself, also generating 'ocomp-sim-0'. Note that while in this case
there is no control allocation is directly specified for the simulation (hence
it not being included in the simulation execution_id), it can also …

bug(ControlMechanism): ensure simulation data and execution_id is unique

---

psyneulink/core/compositions/report.py
tests/composition/test_control.py
tests/mechanisms/test_control_mechanism.py

extracts the simulation number from a simulation context or execution_id

Report: add _get_sim_number function

---

psyneulink/core/components/component.py

When noise is numeric (not generated at Component run time by functions), do not
apply it element-by-element, which can get very slow for large variables.

Component: speed up noise generation for common cases

---

psyneulink/core/compositions/composition.py
psyneulink/core/scheduling/scheduler.py

Scheduler clocks previously were never deleted regardless of `Composition.retain_old_simulation_data` setting

Composition: delete scheduler data when deleting a context

---

psyneulink/core/globals/json.py

it was not reliable/tested in json examples, and it's unclear if there are any
actual examples of manual learning pathways for psyneulink. (all learning
appears to be done via premade methods like
Composition.add_backpropagation_learning_pathway)

json/mdf: ignore learning components when regenerating script

---

psyneulink/library/components/mechanisms/processing/objective/comparatormechanism.py
tests/json/model_backprop.py
tests/json/test_json.py

Ensures that for `ComparatorMechanism`, the `spec` for `input_ports` is correctly assigned to the actual values passed in by the user. Due to unique parsing in `ComparatorMechanism.__init__`, the spec for `input_ports` is a fully parsed port specification dictionary, which is not supported as user-input and consequently is not supported in json methods. Fixes crash in #1997

fix(json/mdf): crash on backprop learning compositions

---

psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py

Fixes a problem in which an incorrect shadowed projection is created from an
OCM/controller to a node. Specifically, consider a composition O with a nested
composition I, containing a node A. If the controller of O has A as its feature,
the controller should only control A and receive shadowed input through the
parameter CIM of I. Prior to this commit, the controller of O received a
shadowed input projection directly from A, created during
_instantiate_input_ports during construction of the controller. This step is
unnecessary and incorrect as shadowed input projections are created during the
call to Composition.add_controller.

fix(OptimizationControlMechanism): don't immediately create shadowed projection for features

---

psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
tests/functions/test_memory.py

• ContentAddressableMemory:  accommodate specification of initializer as scalar, 1d or 2d array that is converted to 3d array for memory
• test_memory:  add tests for above conditions

Fix/content addressable memory/1d 2d initializers

---

psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
tests/functions/test_memory.py

• memoryfunctions.py:
  ContentAddressableMemory:
- allow initializer to be a single entry (i.e., 1d or 2d array)
  - allow variable (entry) to be 1d or regular 2d array
  - clean up np.array casting
  - add classmethod _enforce_memory_shape
  - add validation for distance_field_weights parameter

Fix/content addressable memory/execute 1d 2d entries

---

docs/source/EpisodicMemoryMechanism.rst
psyneulink/core/components/functions/statefulfunctions/memoryfunctions.py
psyneulink/core/components/functions/statefulfunctions/statefulfunction.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/library/components/mechanisms/processing/integrator/episodicmemorymechanism.py
tests/documentation/test_mod_docs.py
tests/functions/test_memory.py
tests/mechanisms/test_episodic_memory.py

• episodicmemorymechanism.py
  - Parameters:  changed default_variable to [0,0] (to avoid warning with Distance(metric=COSINE)
- Examples added to docstring
• test_episodic_memory.py:  added test for default constructor
• test_memory.py:  added explicit tests for duplicate_entries_allowed and duplicate_threshold

Docs/episodic memory mechanism/examples

---

requirements.txt

1.8.0 required in MDF (https://github.com/ModECI/MDF/pull/50) which will soon require psyneulink (https://github.com/ModECI/MDF/pull/44)

requirements: bump pytorch to 1.8.x

---

.github/actions/install-pnl/action.yml
.github/workflows/pnl-ci.yml

Drop pytorch from requirements when using 32-bit python.
Install older pywinpty when using 32-bit python.
This reverts commit 1ace7f9ff141345c7ed9c3a1a2811d883061a4b6.

github-actions: Reintroduce 32-bit windows job

---

.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml
MANIFEST.in

The script is triggered upon creation of prerelease.
It creates dist packages and tests them.
The dist files are uploaded as release assets, and optionally to PyPI.
Fixes sdist distribution package.

github-actions: Add automated release script

---

.github/actions/install-pnl/action.yml

Newer versions pull in new pywinpty.

deps: Restrict terminado to < 0.10 on x86

---

.github/workflows/compare-comment.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py

Use the helper to convert array indices and as_type.
Move float->int conversion from Index to Subscript.
Enable python3.9 CI jobs.

llvm: Add generic conversion helper.

---

conftest.py
tests/functions/test_combination.py
tests/functions/test_default_allocation.py
tests/functions/test_distance.py
tests/functions/test_distribution.py
tests/functions/test_fhn_integrator.py
tests/functions/test_identity.py
tests/functions/test_integrator.py
tests/functions/test_memory.py
tests/functions/test_optimization.py
tests/functions/test_selection.py
tests/functions/test_stability.py
tests/functions/test_transfer.py
tests/functions/test_user_defined_func.py
tests/mechanisms/test_control_mechanism.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_episodic_memory.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_objective_mechanism.py
tests/mechanisms/test_processing_mechanism.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/ports/test_output_ports.py

Provide a helper to construct and select the right execution wrapper for compiled functions.
Provide a helper to construct and select the right execution wrapper for compiled mechanisms.
Pass the execution correct wrapper to the benchmark fixture.

tests: Add and use new execution wrapper helpers

---

psyneulink/core/compositions/composition.py
psyneulink/core/scheduling/scheduler.py

Conditions passed to `termination_processing` of `Composition.run` implicitly updated the base termination conditions for future runs of the scheduler. Instead, only use them for the current run. Rename `Scheduler.update_termination_conditions` to avoid implying that it actually updates the conditions (done by the property instead).

Scheduler: clarify interface for updating base termination conditions 

---

psyneulink/__init__.py
psyneulink/core/compositions/composition.py
psyneulink/core/scheduling/condition.py
psyneulink/core/scheduling/scheduler.py
psyneulink/core/scheduling/time.py
requirements.txt
tests/composition/test_composition.py
tests/scheduling/conftest.py
tests/scheduling/test_condition.py
tests/scheduling/test_scheduler.py

Supports basic absolute/real time scheduling using `TimeInterval` and `TimeTermination`, with fixed-length time steps in both standard mode using the topological scheduling order and exact-time mode in a flattened order
New requirement: `pint<0.18`

scheduling: add absolute time and exact time modes

---

psyneulink/core/components/functions/userdefinedfunction.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py
tests/functions/test_user_defined_func.py

Extend test parametrization to cover more corner cases.
Add support for expressions of non-boolean type in if condition.
Add support for non-boolean values in boolean expressions.
Add support for subtraction and power operators.
Add support for unary add and not.
Fix return statements to return from the function instead of just updating the return value.
Allocate variable space for variable storage, the type is derived from the first occurrence of the variable in code.
Fix the NaN behavior of Python and numpy max builtins.
Refactor expression generation to not use stack space for constructing temporary values (with the exception of subscript).

llvm: Update and refactor the UDF compiler

---

psyneulink/core/components/ports/parameterport.py
tests/ports/test_parameter_ports.py

A class might have a modulable Parameter with the same name as a modulable Parameter on one of its functions. Previously, this would silently only create a single ParameterPort for the function's parameter. These changes cause the creation of ParameterPorts for both, with each suffixed in a similar manner as when there is a conflict between ParameterPorts with the same name across multiple functions. The suffix for the main object's port is `self`.

fix(parameter ports): handle same name param on obj and its functions

---

.github/workflows/prepare-release.yml

Two things happen when a tag is pushed to master:
* the tagged commit is merged back to devel
* a new pre-release is created (which trigger test-release workflow)
Creating a release needs PAT with public_repo privilege level in order
to trigger the test-release workflow.
The default actions token does not trigger workflows on repo actions.
If token is set to 'no-token' the pre-release creation is skipped.

github-actions: Prepare pre-release on tag on master

---

psyneulink/__init__.py
psyneulink/core/scheduling/condition.py
psyneulink/core/scheduling/scheduler.py
psyneulink/core/scheduling/time.py
tests/scheduling/test_condition.py

Conditions sometimes failed to be satisfied when they otherwise should have due to floating point precision issues. Times now avoid floats when possible but limit precision to 8 decimal points when not.

scheduling: account for floating point errors for absolute time

---

.github/actions/on-branch/action.yml
.github/workflows/compare-comment.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/prepare-release.yml

Unify documentation testing and comparison.
Switch the comment posting workflow to use generated documentation artifacts.
The old docs-compare workflow can be removed after the modified comment posting lands in the default branch.

github-actions: Consolidate documentation jobs

---

.github/workflows/compare-comment.yml
.github/workflows/pnl-ci-docs.yml

workflows started by other workflows cannot access the PR
number of the original if the PR branch is from a fork. This causes
compare-comment to not be able to download pnl-ci-docs artifacts
See https://github.com/PrincetonUniversity/PsyNeuLink/runs/3317202966?check_suite_focus=true corresponding to #2103

ci: fix missing PR number

---

psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py
tests/functions/test_user_defined_func.py
tests/models/test_greedy_agent.py

Needs custom UDF to calculate the weighted move.
This also introduces new nodes to handle inputs, and a node to calculate the direction from real player to prey.
Add support for np.sqrt to the UDF compiler.

 tests/models/Predator-Prey: Use attractor/repeller forces to select the next move

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
tests/composition/test_control.py

Use IntFlag for cost functions

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/userdefinedfunction.py
tests/functions/test_user_defined_func.py

- Support passing parameters into UDF init as normal keyword arguments 
- Support custom functions defined as basic string expressions (no function calls)
- Support integration for one custom parameter using the `stateful_parameter` argument

UDF improvements

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/distributionfunctions.py
psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
tests/composition/test_control.py
tests/functions/test_distribution.py
tests/models/test_greedy_agent.py

Drop unused parameters.
Optionally save generated values.
Implement compiled uniform distribution function.

llvm: Add missing functionality to OCM

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/distributionfunctions.py
psyneulink/core/components/functions/nonstateful/selectionfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_control.py

Store used seed in compiled random state.
Check the last used seed with the most recent value of the 'seed' param,
reseed the random state if the seeds don't match.
Add simple test.

llvm: Add helper function to retrieve and optionally reseed random state

---

.github/workflows/pnl-ci.yml

Block macos-11 until
https://github.com/actions/virtual-environments/issues/4230 is fixed

github-actions: Restrict main CI run to macos-10.15

---

.github/workflows/pnl-ci.yml

github-actions: Do not check for GITHUB_TOKEN env var when uploading coveralls result

---

.github/workflows/pnl-ci-docs.yml

Per [0] this should also work with dependabot triggered runs on devel.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2144
Tested by setting default GITHUB_TOKEN permissions to RO at repo scope.
[0] https://github.blog/changelog/2021-10-06-github-actions-workflows-triggered-by-dependabot-prs-will-respect-permissions-key-in-workflows/

github-actions: Allow RW permissions for jobs updating the online docs

---

.github/workflows/pnl-ci-docs.yml

Cleanup the tag if the documentation build fails.

github-actions/pnl-ci-docs: Force creation of temporary version tag

---

tests/mechanisms/test_ddm_mechanism.py

Disable to investigate segfaults:
=================================== FAILURES ===================================
____________________ tests/mechanisms/test_ddm_mechanism.py ____________________
[gw2] darwin -- Python 3.7.12 /Users/runner/work/_temp/_venv/bin/python
worker 'gw2' crashed while running 'tests/mechanisms/test_ddm_mechanism.py::test_DDM_Integrator_Bogacz[LLVM-Philox]'
=============================== warnings summary ===============================

tests/ddm: Disable Bogacz test with Philox prng

---

.github/workflows/compare-comment.yml

Follow up to 01f710683a7ff6c163fe990700666af047bf9473
("github-actions/release: rest API methods were moved to github.rest.*")
Fixes: 35cf6ecc792f0dd4bb024510b37b3ff825560ab0 ("github-actions(deps):
bump actions/github-script from 4.1 to 5 (#2125)")

github-actions/comment: Add PR write permission and use github.rest.* for rest API

---

psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/compositions/autodiffcomposition.py
tests/mechanisms/test_ddm_mechanism.py

Pass the mechanism params and state when retrieving DDM mechanism random state
Use correct helper to get composition state.
Add state id for autodiff optimizer state.
Add basic sanity checks to get_{param,state}_ptr helpers.

llvm: Check for correct use of get_{param,state}_ptr helpers

---

tests/models/test_greedy_agent.py

tests/models/predator-prey: Restore checks of results

---

psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
tests/composition/test_control.py

Add necessary shape workarounds to support compiled CostFunctions.NONE.
Fix and enable tests.
Add extra check for simulation input construction.

llvm, ports/ControlSignal: Add support for CostFunctions.NONE

---

tests/models/test_greedy_agent.py

No reason to run this variant in regular testing.

tests/predator-prey: Mark the 101 level test instance as 'stress' test

---

.github/workflows/pnl-ci.yml

now that jenkins builds are not produced and the required status is on
actions, we need actions to build these

pnl-ci: build docs-only branches

---

psyneulink/core/llvm/debug.py
psyneulink/core/llvm/execution.py

Allow arbitrary attribute names for caching binary structures.
Report time to generate binary functions.

llvm: Cleanup execution of compiled functions

---

setup.cfg

setup/coverage: Correct option name multiprocess -> multiprocessing

---

tests/composition/test_show_graph.py

Spaces and newlines should not matter.
Fixes test failures with graphviz==0.19 which added extra newline at the end of output.

tests/show_graph: Strip whitespace before comparing expected dot output

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/learningfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py

parameters with getters would not be called during initialization due to
condition order, and as a result values would not be populated.
Component: set variable to default when determined in init

Component: _initialize_parameters: always ensure None context set

---

psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/compositions/composition.py

- initialize context for when an agent_rep uses a controller other than
its self.controller
(ex. test_nested_composition_as_agent_rep)
- add Composition._initialize_as_agent_rep and
Composition._clean_up_as_agent_rep

OCM: improve simulation context setup

---

psyneulink/core/components/functions/nonstateful/selectionfunctions.py
tests/functions/test_selection.py
tests/mechanisms/test_processing_mechanism.py

Enable compiled test of MAX_ABS_ONE_HOT output port. (#1780)

llvm, functions/OneHot: MAX_ABS_VAL should return absolute value of the greatest magnitude

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/nonstateful/distributionfunctions.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py
psyneulink/core/globals/utilities.py
tests/mechanisms/test_mechanisms.py

Noise values are either numeric or contain functions. A ParameterPort is generated for noise only when the noise value is numeric at the time of mechanism construction. These changes make the noise parameter stateless when it contains functions and warn the user that the previously mentioned properties will not change if the user changes the value of noise after function construction.

functions: noise properties based on numeric or function

---

psyneulink/core/components/ports/port.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/codegen.py
tests/functions/test_user_defined_func.py

Rename port function tmp var to match the 'port' name.
Add human-readable stack slot names to UDF local variables.
Drop handling of unused parameter.
Add extra check when selecting Philox vs. Mersenne-Twister

llvm: Cleanup

---

psyneulink/core/components/functions/stateful/integratorfunctions.py
tests/functions/test_integrator.py

This is helpful for testing the compiled Threshold condition

llvm, functions/AccumulatorIntegrator: Add compilation support

---

psyneulink/core/components/component.py

Drop 'allocation_samples' the values are replicated in 'search_space'.
Drop 'num_executions' from most components. It's only used by Composition and Mechanism

llvm: Drop redundant parameters from compiled structures

---

psyneulink/core/components/mechanisms/processing/transfermechanism.py

shape of integration_rate should at least be checked against exact shape
of default variable otherwise some valid configs fail (ex. rate and
variable = [[0], [0]])

TransferMechanism: fix integration_rate validation

---

psyneulink/core/llvm/helpers.py
tests/llvm/test_helpers.py

Add better testing for both is_close and all_close

llvm/helpers: all_close should compare elements from both input arrays

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/components/ports/port.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/debug.py
psyneulink/core/llvm/execution.py
psyneulink/core/llvm/helpers.py
psyneulink/core/llvm/jit_engine.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/llvm/test_debug_composition.py

Do not create a copy of parameters if there are no parameter states.
Add memcopy helper to W/A heavy register usage by store(load(src), dst) idiom.
Upload base arguments to on-chip 'shared' memory for GPU evaluate (optional, default ON).
Add human-readable names to alloca instructions.
Drop unused 'evaluate' kernel wrapper code.
Drop 'cuda_data' debug switch.
Improves performance ~2.5x for both CPU and GPU execution (measured using predator-prey model with 101 levels of attention)

llvm/{cuda,}: Reduce and optimize data copies in model execution

---

tests/composition/test_control.py
tests/llvm/test_builtins_intrinsics.py
tests/llvm/test_builtins_matrix.py
tests/mechanisms/test_episodic_memory.py
tests/mechanisms/test_transfer_mechanism.py

Add a test modulating DDM seed in analytical mode.
Use helper function to select the right execution mode.
Small style cleanups.

tests: small cleanup

---

psyneulink/core/components/component.py
psyneulink/core/components/ports/port.py

Do not create a private copy of port parameters if there is no modulation other than override.
Drop more unused parameters from the binary parameter structure.

llvm: Reduce the amount of data copied due to parameter modulation

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/execution.py

Restrict 'has_initializers' parameter to mechanisms. This leaves most functions with parameters that are modified by parameter ports.
Don't copy base parameters to private parameter space if all of them will be replaced by parameter port outputs.
Use mechanism base params structure in places that don't modify parameters via parameter ports (e.g. running input/output ports). Unlike the modified result, which is private per evaluation, the base structure is shared.
This improves cache performance and memory utilization for both CPUs and GPUs.

llvm/cuda: Optimize memory copies in memory execution

---

psyneulink/core/llvm/jit_engine.py

The threshold is empirically determined using the predator-prey model.
Number of function calls (static) changes:
model | before | inline0 | inline4 | inline6 | inline7 | inline8
p-p   | 287    | 195     | 162     |  123    |  121    | 125
s-f   | 413    | 221     | 206     |  156    |  155    | 164
This significantly reduces GPU stalls because of instruction fetch
(measured on P620)
(pp-MT/pp-Philox): 10.99%/18.21% -> 5.06%/8.46%
(sf-MT/sf-Philox): 36.72%/38.96% -> 19.1%/22.2%
as well as the amount of private data read/written.
This combines to ~15-20% (pp) improvement in kernel runtime.

llvm/cuda: Enable function inlining in CUDA path

---

psyneulink/core/components/projections/projection.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/socket.py
psyneulink/core/scheduling/scheduler.py
tests/composition/test_composition.py

Updates node removal with tested cases
Methods added:
- Composition.remove_node
- Projection.is_active_in_composition

Add node removal to Compositions

---

requirements.txt

Should be able to be removed at next modeci_mdf release, see https://github.com/ModECI/MDF/pull/215

requirements: restrict modelspec to working

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/llvm/builtins.py

Add missing name to alloca instruction.
Use more descriptive variable names when invoking simulation trials.
Use conditional select instead of a stack array in the initialization of Mersenne Twister.

llvm: More descriptive variable names

---

.github/workflows/pnl-ci-docs.yml

When there are multiple tags pointing to the HEAD commit,
git describe returns the first in alphabetical order.
Use v0.0.0.0 to have deterministic description
even if there is another tag pointing to the HEAD commit.
Fixes: 65967d9e1f67891b4bbb771ed5670cea5ea2eac3
("ci: increase fetch depth and tags")

github-actions: Use v0.0.0.0 as dummy tag to compare documentation on pull requests

---

psyneulink/core/components/component.py

no longer needed due to shared_types and copy_iterable_with_shared

Component: don't exclude _init_args from deepcopy

---

psyneulink/core/compositions/composition.py
tests/composition/test_composition.py

if a TERMINAL node in a Composition that was not in the final
consideration set had an inactive projection to another node, the
TERMINAL role was not assigned because the active/inactive status was
not considered

Composition: fix TERMINAL node detection

---

.github/actions/install-pnl/action.yml

Check all requirements files.
Account for -/_ ambiguity in package names.
Skip the check when building the "base" documentation variant.
Fixes: 0aa4359c88b6995577cf30d9df18bcdac3ce2731
("github-actions/pnl-install: Check if a newly bumped dependency is
rolled back during installation (#2390)")

github-actions/install-pnl: Fix lookup of dep packages

---

.github/workflows/pnl-ci-docs.yml

This avoids cascading errors if the workload fails before the tag was added.

github-actions/pnl-ci-docs: Skip removing the zero tag if tag creation was skipped

---

psyneulink/core/globals/parameters.py
tests/misc/test_parameters.py

having a _set_<attr> method for each member is needed to avoid checking
parents as if it were an inherited attribute

tests: Parameters: add check for _additional_param_attr_properties

---

psyneulink/library/components/mechanisms/processing/transfer/kwtamechanism.py

auto and hetero were always treated as user_specified

KWTAMechanism: set matrix according to tests

---

requirements.txt

The versioning scheme uses 1.10.y, 1.11.v, ... instead of bumping to
2.0.x.
This reverts commit 70aa4923ea6f89fe0107206d7f159665a0544675.

Revert "requirements: update pytorch requirement from <1.9.0 to <2.0.0"

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/mechanisms/processing/processingmechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/functions/test_transfer.py
tests/mechanisms/test_processing_mechanism.py

Convert MAX_VAL, and MAX_INDICATOR SoftMax output types to use OneHot nested function.
Add support for PROB SoftMax output type.
Add support for compiling PROB standard output.
Check that we're not using combination_function in compiled RTM.
Drop nested parameters and state of combination function if not used in RTM.

llvm: Add support for more SoftMax output types

---

psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py

LCControlMechanism and DDM both modify function return values before using them as mechanism values.
Overloading _gen_llvm_mechanism_functions instead of _gen_llvm_invoke_function gives direct
access to modulated mechanism parameters without accessing the LLVM function arguments.
Use helper functions instead of explicitly checking types when possible.
Drop no longer needed shape workarounds.

llvm: Cleanup codegen of mechanisms that modify function return value

---

psyneulink/core/components/functions/stateful/integratorfunctions.py

lower dimensions cause crash because Angle uses dimension-1 and has a
lower limit of dimension 2

DriftOnASphereIntegrator: change default dimension to 3

---

psyneulink/core/compositions/composition.py
tests/composition/test_composition.py

Node roles may be specified in various places, including when specifying
a Pathway. These roles can imply that some projections should be
feedback, and it can be cumbersome to check for these in any place
add_projection may be called to pass feedback=True.
This checks for these roles in Composition.add_projection when adding an
edge to the Graph.
Fixes #2004

Composition: add_projection: also detect feedback from node roles

---

tests/json/test_json.py

prevents need to manually determine values based on OS or onnxruntime
version

JSON/MDF: determine fixed onnx noise values at test time

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py

The new approach reuses existing parallel/compilation support in '_evaluate' and calls compiled search on the result.

functions/GridSearch: Refactor parallel compiled path to reuse existing '_evaluate' implementation

---

.github/workflows/pnl-ci.yml

Python 3.7 is broken on macos-11 [0],
at the same time macos-10.15 will be removed by github-actions[1].
[0] https://github.com/actions/virtual-environments/issues/4230
[1] https://github.com/actions/virtual-environments/issues/5583

github-actions: Drop python3.7 macos job

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/ports/port.py
psyneulink/core/compositions/composition.py
psyneulink/core/globals/log.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py
tests/components/test_general.py
tests/composition/test_composition.py
tests/composition/test_show_graph.py
tests/functions/test_user_defined_func.py
tests/mechanisms/test_input_state_spec.py
tests/mechanisms/test_kwta.py

E275 reported by the new pycodestyle package (v2.9.0)

treewide: Add missing whitespace after keyword

---

psyneulink/core/components/functions/userdefinedfunction.py
psyneulink/core/llvm/execution.py
tests/functions/test_transfer.py
tests/llvm/test_multiple_executions.py

Use 'bytes' instead of 'bytearray' for RO view of ctype structures.
Use np.where instead of custom transformation.
User dir(builtins) instead of __builtins__ .

simple cleanups

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/llvm/execution.py
psyneulink/core/llvm/helpers.py

This will make it easier to pass inputs for multiple trials.
Avoids duplicate construction of "predicted input" in each evaluation.
Allows better used of shared memory in GPU execution.

llvm: Switch 'evaluate' to consume simulation input

---

requirements.txt

@davidt0x @kmantel I think this is a better way to specify dependencies for mdf/modelspec. PNL doesn't explicilty use modelspec, so should leave which version to use to mdf's dependencies. 
This form for the dependency will mean it will use the latest mdf 0.4.x version. If we introduce a breaking change we bump mdf to 0.5.x and updated the dependency in pnl only then.

Better requirements on MDF

---

psyneulink/core/llvm/execution.py

The original code assumed 'run' variant would be called.
This is not the case for parallel evaluate that only needs
'run, simulation' variant, resulting in redundant code generation and compiler
calls.
Instead, just use the 'evaluate' function that provides the
same binary type at a different argument location.
Tested by asserting that Python-{LLVM,PTX} tests only generate
'run, simulation' variant of the composition function.

llvm/execution: Use 'evaluate' function params when constructing simulation input

---

tests/mechanisms/test_transfer_mechanism.py

"EX" represents the right invocation variant;  compiled or GPU or Python execution,
use that instead of always executing Python version.
Fixes: cf57224670a0830dd555f34e04c0d4a083d3b996
("test/mechanisms/TransferMechanism: Only run benchmarks if enabled")

tests/TransferMechanism: Use the correct execution mode in test_transfer_mech_integration_rate_0_8

---

tests/composition/test_control.py
tests/functions/test_user_defined_func.py
tests/mechanisms/test_control_mechanism.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_lca.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/ports/test_output_ports.py
tests/scheduling/test_condition.py
tests/scheduling/test_scheduler.py

Add missing pytest.mark.composition to test that construct and run Composition.

tests, treewide: Add missing "composition" marks

---

requirements.txt

modeci_mdf pulls in pytorch[0] so it needs the same constraints.
[0] https://github.com/ModECI/MDF/blob/main/setup.cfg

requirements: Restrict modeci_mdf to 64bit cpython

---

.github/actions/install-pnl/action.yml

Some packages may pull in updated dependencies and can't handle those dependencies being rolled back during PNL install.

github-actions/install-pnl: Cleanup installation of the bumped package before installing PNL

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

The packages should be rebuilt if some of the shared dependencies change

github-actions: Add hash of requirements.txt to cache key of built pip packages

---

.github/actions/install-pnl/action.yml

This happens if the package is a dependency with 'extras', e.g. a 'doc' or 'cuda' dependency not installed in 'dev' CI jobs.
Fixes package bumps of docs dependencies.

github-actions/install-pnl/dependabot_pr: Skip package version check for not installed packages

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/integratormechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/projections/projection.py
tests/mdf/test_mdf.py

- DriftDiffusionIntegrator exportable into MDF with equivalent results
- organizational changes to general psyneulink MDF export code to make it easier to add MDF support for more complex psyneulink Functions

MDF: support DriftDiffusionIntegrator

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/mechanisms/test_ddm_mechanism.py

Consistently use modulated mechanism parameters (e.g. threshold) of TransferMechanism in `is_finished` function whether it's called from inside the mechanism loop, or by the scheduler.
Use modulated function parameters in DDM's 'is_finished' function in both internal and scheduler invocation.

llvm: Use modulated parameter values in 'is_finished' variant

---

.github/actions/install-pnl/action.yml

scipy doesn't provide 32-bit wheels for 1.9.2

github-actions: Restrict scipy to <1.9.2 on x86

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/llvm/execution.py

The only supported evaluation type atm is "evaluate_type_objective", which uses the result of ocm.objective_mechanism as output (combined with costs).

llvm, ocm/evaluate: Add basic support for multiple evaluation_types

---

.github/actions/install-pnl/action.yml
.github/actions/on-branch/action.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml

The old way of using workflow commands is going away[0]
[0] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

github-actions: Use environment files to set outputs

---

.github/actions/install-pnl/action.yml

scikit-learn doesn't provide 32-bit wheels for >=1.1.3

github-actions: Restrict scikit-learn to <1.1.3 on x86

---

.github/actions/install-pnl/action.yml
.github/actions/on-branch/action.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml

Use correct format of outputs written to GITHUB_OUTPUT.
Consider additional dependency files (dev_, doc_) when creating cache keys.

github-actions: Fix detection of wheel cache directory location

---

.github/actions/install-pnl/action.yml

statsmodels doesn't provide 32-bit wheels for >=0.13.3, and the build process tries to pull in scipy-1.9.3 triggering the issue that was addressed in e607c0973f74eceb514c2de9eb6e3ae7dfa29716 [0]
[0] https://github.com/PrincetonUniversity/PsyNeuLink/actions/runs/3371876413/jobs/5594642498

github-actions: Restrict statsmodels to <0.13.3 on x86

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/core/llvm/jit_engine.py
tests/functions/test_transfer.py
tests/llvm/test_builtins_intrinsics.py

Switch to fixed implementation of ReLU derivative in both Python and compiled variant.
Use input consistently in SoftMax derivative (Python).
Add sin and cos builtin functions, PTX can't select instructions for llvm.sin/llvm.cos opcodes.

llvm: Implement compiled Angle and SoftMax derivative Functions

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/compositions/composition.py
psyneulink/core/compositions/pathway.py
setup.cfg
tests/composition/test_control.py
versioneer.py

The escape sequences were ignored so we can just remove the escaping '\'.
Check that the required warning is present at any position in "test_model_based_num_estimates".
Use raw string when listing code in versioneer.py.
Change warning for invalid escape sequences to error.

docs: Remove invalid escape sequences

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/llvm/jit_engine.py
tests/functions/test_transfer.py

Use the correct index for max_val in Python version.
Remove the outer dimensions in the compiled version.
Add tests

functions/SoftMax: Add support for 2d inputs to SoftMax derivative

---

conftest.py
psyneulink/__init__.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/gating/gatingmechanism.py
psyneulink/core/globals/registry.py
psyneulink/library/components/mechanisms/modulatory/control/agt/agtcontrolmechanism.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py

The names of components instantiated during test enumeration depend on the order in which the tests are enumerated and shouldn't be used.
Introduce a concept of reserved names (names beginning with "__pnl_" and add a mechanism to add a custom reserved prefix to all generated Component names.
Use the new mechanism to add a common prefix to all Components instantiated during test enumeration.
This makes sure that the names of such components don't conflict with names autogenerated during test execution.
It also makes it easier to detect if any test depends on the name of a Component passed via a parameter.

tests: Use custom name prefix for Components instantiated during test enumeration.

---

.github/workflows/pnl-ci.yml

Checks setting one of the following secrets:
SELF_HOSTED_MACOS, SELF_HOSTED_LINUX, SELF_HOSTED_WINDOWS
If the value stored in any of them evaluates to true (based on GitHub actions expression truth values) the jobs for the respective OS will be tagged to use self-hosted runners.
Without the secret, jobs will use GitHub cloud runners.
"runs-on" doesn't allow direct use of environment variables so we need to pass them via an extra job.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2526

github-actions: Check CI secret to tag selected OSes to run on self-hosted runners

---

.github/actions/install-pnl/action.yml

jupyter pulls in jupyter-server-terminals which requires pywinpty>=2.0.3 on windows [0]
[0] https://github.com/jupyter-server/jupyter_server_terminals/blob/main/pyproject.toml

github-actions/install-pnl: Restrict jupyter-server to <2

---

.github/workflows/codeql.yml

github-actions/codeql: Skip CI job on pushes that only update documentation

---

psyneulink/core/components/mechanisms/mechanism.py
tests/mechanisms/test_kwta.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py

String values of errors are not stable and can change between versions.
Fixes 'input_list_of_strings' tests when using numpy>=1.22.x.
Refactor handling of input port execution exceptions to only check calls to 'execute', parameter set/get do not throw exceptions.

tests/mechanism: Do not check for string value of numpy error embedded in MechanismError

---

requirements.txt

Calling gcd on list comprehension fails with numpy<1.19.0
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2581

requirements: Bump minimum numpy version to 1.19.0

---

.github/actions/install-pnl/action.yml

Some python packages no longer provide x86 (32bit) wheels, and the CI build environment is not good enough to build all of them from source. Restrict versions of these packages in `env_contraints.txt` instead of pre-installing the old versions.

github-actions: Use constraints file instead of pre-installing packages on x86

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/projections/projection.py
psyneulink/core/llvm/codegen.py
tests/composition/test_control.py

Add "passthrough" variant to Projection execution.
Passthrough mode does not invoke the projection function.
This is used to pass modulatory values before the execution starts.
Execute modulatory projections in "passthrogh mode" when calling node wrapper for node reset.
Rename projection origin from 'parent'->'sender'
Apply modulation before calling function "reset" in mechanism.
Add tests.

llvm, Mechanism: Apply modulation to initializers during node reset

---

tests/mechanisms/test_transfer_mechanism.py

test contained the same values for function initializer and initial_value, but meant to test that the function initializer overrode the initial_value

tests: correct transfer mech initial_value override test

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py

bounds are checked only during reset, and the default value of search_space causes this to fail (lower == upper)

GradientOptimization: stop error on default bounds

---

psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/library/components/mechanisms/processing/integrator/episodicmemorymechanism.py
tests/mechanisms/test_episodic_memory.py

Shared with its function initializer. Changes conflict behavior to be consistent with other SharedParameters (function value favored over owner value). For discussion on this, see https://github.com/PrincetonUniversity/PsyNeuLink/issues/2600

EpisodicMemoryMechanism: make memory (_memory_init) a FunctionParameter

---

.github/actions/install-pnl/action.yml
broken_trans_deps.txt

Add onnxruntime-1.14.0 on macos to the constraint. https://github.com/microsoft/onnxruntime/issues/14663

github-actions: Constraint broken transitive dependencies

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/components/ports/port.py
psyneulink/core/globals/__init__.py
psyneulink/core/globals/warnings.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/warnings.py

Introduce two new warning categories: `PNLInternalWarning` and `PNLUserWarning`.
Internal wanting are set to "ignore" by default.
This default can be overridden by calling private `_enable_internal_warnings` function.
Add a new  `PNLCompilerWarning` category, derived from `PNLInternalWarning`, (and thus ignored by default),
and switch all "shape mismatch" warning cases to use `PNLCompilerWarning`.
pytest overrides warning filters so test issued warnings are not affected.

Add PNL specific warning categories

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/ports/port.py
psyneulink/core/components/projections/projection.py
psyneulink/core/compositions/composition.py
psyneulink/core/compositions/pathway.py
tests/composition/test_composition.py
tests/composition/test_interfaces.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_modulatory_mechanism.py
tests/ports/test_input_ports.py

ControlMechanisms that control something within an inner Composition automatically create MappingProjections to the inner Composition's parameter CIM. This created a scheduling dependency in all cases. These changes cause this dependency to be created only when the pathway/projection from the ControlMechanism to the inner Composition is explicitly created by the user.

Composition: fix INPUT roles for ControlMechanism -> inner Composition

---

psyneulink/core/llvm/builder_context.py

llvm: Use weak references and proxy objects in _node_wrapper objects

---

tests/llvm/test_multiple_executions.py

assert_allclose checks the shape of compared arrays as well as the values.
Drop explicit checks for the size of the outer dimension.

tests/llvm/multiple_executions: Use np.testing.assert_allclose to check results

---

dev_requirements.txt
requirements.txt
tutorial_requirements.txt

Drop grpcio-tools, switch to protobuf.
Use tighter bound on dill.

requirements: Use sharp upper bounds and maintain alphabetical order

---

.github/workflows/pnl-ci.yml
tests/composition/test_autodiffcomposition.py

This does not monitor performance, it just checks that the tests pass if the benchmark fixture runs multiple iterations of the benchmarked call.

ci: add run using --benchmark-enable

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py

Rename incorrectly named "state_features".

llvm: Remove unnecessary shape checks and workarounds

---

psyneulink/core/globals/registry.py

Fixes:3c9662d8a3946acfcd70093553f694ff1c4792b5
("registry: Add configurable prefix to auto generated component names")
Fixes failures when run in "forked" mode (pytest --forked).

registry: Apply prefix to autogenerated names for the first instance

---

psyneulink/core/components/component.py

This reduces the size of "params" compiled structure by 20-30% in learning tests in the test suite.

component: Add unused learning parameters to compilation blocklist

---

broken_trans_deps.txt

https://github.com/ipython/ipython/issues/14053

ci: Add ipython 8.13.0 to blocklist for python <3.9

---

tests/composition/test_composition.py

np.allclose call was not asserted since this test was added. The results for this call changed in
0946af083f2f1cab23f0dfd6c0ee05b81b765500 (#1639) due to a change in default for argument loss_spec (formerly loss_function) from None to MSE in add_linear_learning_pathway and
_create_backpropagation_learning_pathway.
As of this commit, changing these defaults back to None produces the numeric results that were present when this test was created.
The allclose call also misinterpreted the return value for Composition.run as producing multiple trial outputs that are instead in Composition.results

tests: test_call_after_construction_with_learning_pathway: fix missing assert

---

requirements.txt

Optuna uses patch version to release bugfixes[0],
set the cap the next minor version.
[0] https://github.com/optuna/optuna/releases

requirements: Use exclusive upper bound for optuna

---

.github/workflows/pnl-ci.yml
dev_requirements.txt
psyneulink/core/components/component.py
psyneulink/core/globals/registry.py

Fixes the "default_MappingProjection_names" test failure when the test is run as the first test in testing session:
"pytest -n0 -k test_deferred_init_default_MappingProjection_names"

Component: Add predefined prefix to autogenerated names in deferred init

---

dev_requirements.txt
setup.cfg

tests: Use worksteal xdist balancer

---

.github/workflows/pnl-ci.yml
requirements.txt
tests/functions/test_distribution.py

Numpy 1.23 reimplemented tanh function [0,1], which changed the result of
positive skew result for small drift rate.
[0] numpy/numpy#20363
[1] numpy/numpy@75edab9

requirements: update numpy requirement from <1.22.5 to <1.23.6

---

tests/functions/test_functions.py

Since each test uses incrementing fixed seeds from 0, using new_seed = 1 will cause it to share a seed with some other component, depending on the order in which components are created (ex: one Parameter is instantiated before or after another, resulting in different individual seeds for each).
This ensures that new_seed will actually be unused in the test.

tests: ensure seed change test uses new seed

---

psyneulink/core/globals/sampleiterator.py

SampleIterator: Fix incorrect use of curly brackets in error strings

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/globals/parameters.py
psyneulink/library/components/mechanisms/processing/transfer/lcamechanism.py

- don't suppress AttributeError within _parse/_validate methods
removed:
- `Parameters._get_prefixed_method`
added:
- `Parameters._get_parse_method`
- `Parameters._get_validate_method`

Rework Parameter parse/validation method calling

---

psyneulink/core/globals/utilities.py
psyneulink/core/llvm/builder_context.py
requirements.txt
tests/composition/test_composition.py
tests/llvm/test_builtins_mt_random.py
tests/llvm/test_builtins_philox_random.py
tests/llvm/test_custom_func.py
tests/llvm/test_helpers.py

Numpy 1.24 removes few deprecated features and introduces new deprecations;
* construction of rugged arrays now throws ValueError.
* Update `safe_create_np_array` to handle both the original DeprecationWarning and the new ValueError
* Extract values of all mechanisms in `test_save_state_before_simulations` to avoid rugged array
* Conversion from Python integer types warns on range overflow.
* Switch representation of ctype integers to unsigned. Most uses expect unsigned results.

dependencies: Update to numpy<1.24.4

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
setup.py

Add Python 3.11 to the list of supported Python versions.
Add documentation build using Python 3.10 and 3.11 to CI.
Bump used Python version in CI jobs to Python 3.11.
Switch "--benchmark-enable" and "--fp-precision=fp32"  CI jobs to Python 3.10.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2681

Support and test Python 3.11

---

.github/actions/install-pnl/action.yml

deps: Restrict contourpy to <1.1.0 on x86 (32-bit)

---

.github/workflows/pnl-ci-docs.yml

Python version used by the setup-python action is missing bz2 module:
https://github.com/actions/setup-python/issues/682
Don't build "base" version of docs using python 3.10 and 3.11

ci: Don't use python 3.7.17 on macos to build docs

---

conftest.py
tests/llvm/test_debug_composition.py

Add power_set helper.
Remove duplicate debug flag from the tested list.
Use the new helper to generate all test variants.

tests: Add helper to generate power set and use it to test compiler debug options

---

.github/workflows/pnl-ci.yml

Use "--benchmark-only" together "-m benchmark".
The former will fail if benchmarking is not available. The latter works around a bug in pytest test collection:
https://github.com/ionelmc/pytest-benchmark/issues/243
Fixes: d6f8e35c49fed00468944a3e868e0132ebeb83f2
("tests: Use worksteal xdist balancer (#2670)")

ci: Disable pytest-xdist in benchmark ci job

---

conftest.py
psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/execution.py
tests/functions/test_memory.py
tests/functions/test_transfer.py

Use Flag instead of IntFlag for cost flags.
Add test testing all cost combinations.
Implement invocation of cost functions.
Writeback stateful parameters after execution of compiled functions and mechanisms.
Writeback stateful parameters back to CPU memory after GPU execution.

llvm, functions: Implement cost calculation in TransferWithCosts functions

---

tests/functions/test_transfer.py

Automatically excluded in python 3.11,
but earlier versions need explicit exclusion.

tests/TransferWithCost: Do not include CostFunctions.ALL when constructing power set

---

psyneulink/core/llvm/execution.py

"random_state" needs conversion to Python RandomState structure.
Do not create numpy arrays of empty structures.

llvm: Only write back shareable data

---

psyneulink/core/components/ports/port.py

• port.py
_parse_port_spec(): fix assignment of port if port_spec[PORT_SPEC_ARG] is a dict with a projection specified

Fix/ parse port spec port as sender or recvr

---

psyneulink/core/components/ports/modulatorysignals/controlsignal.py
tests/composition/test_control.py

The function (TransferWithCosts) calculates costs during execution. The expected results for the modulation simple test reflect halving of calculated costs: [20, 24, 28, 32, 36] -> [10, 12, 14, 16, 18]
Partly closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2721

ControlSignal: Do not recalculate costs on Port._update

---

psyneulink/core/llvm/execution.py

Print input structure information
Print evaluate output structure information.

llvm: Add more structure stat messages

---

psyneulink/core/llvm/builder_context.py
tests/composition/test_parameterestimationcomposition.py

The size of the input array is dynamically determined so it can't use static allocation of GPU shared memory.
Enable PEC GPU tests.

llvm/cuda: Do not use shared memory for inputs

---

psyneulink/core/components/component.py
psyneulink/library/components/projections/pathway/autoassociativeprojection.py
tests/components/test_component.py

- these should be passed to throw standard python or psyneulink errors
- in this case, make the source of a python unexpected argument error more clear
- remove unexpected arguments auto and hetero from AutoAssociativeProjection function init

Component: don't prune args to function init 

---

psyneulink/core/globals/parameters.py
tests/misc/test_parameters.py

Correct bug where a Parameter dependency would fail to be respected if a Parameter P specified its dependency on Parameter Q as a Parameter and not the string 'Q', and Q had a dependency of its own

Parameters: handle Parameters as dependencies

---

psyneulink/core/components/mechanisms/modulatory/control/controlmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/gating/gatingmechanism.py

Avoid unnecessary parsing in `__init__`, and use Parameter parse/validate methods when possible. This avoids always indicating they are user-specified and also parses values if they are later set externally.

Simplify some ControlMechanism arg parsing/validation

---

psyneulink/library/components/mechanisms/processing/objective/predictionerrormechanism.py

input_ports from sample and target is handled in ComparatorMechanism

PredictionErrorMechanism: pass up only sample and target

---

tests/composition/test_emcomposition.py

mark is used to skip pytorch tests on some CI runs

tests: mark em_composition TestExecution as pytorch

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/userdefinedfunction.py
psyneulink/core/components/mechanisms/modulatory/control/gating/gatingmechanism.py
psyneulink/core/components/mechanisms/processing/objectivemechanism.py
tests/components/test_component.py

- disallow using a Parameter's name as an argument when it has a constructor_argument
- add `Component._validate_arguments`
- throw clearer errors for exact reason an argument is invalid (replacing generic message from former `_handle_illegal_kwargs`)
- add `Component._parse_arguments`
- match parameter values from `Parameter.constructor_argument`s and aliases to their original names

Rework handling of parameter arguments to Component constructor

---

tests/composition/test_parameterestimationcomposition.py

Reduce running time.
Provide expected results for different optimization methods

tests:ParameterEstimationComposition

---

psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
tests/composition/test_control.py

Execute OCM ports when setting an allocation.
Reuse calculated costs from TransferWithCosts.
Drop "allocation" parameter to net_outcome.
Consolidate model_based_ocm tests.

llvm, OptimizationControlMechanism: Reuse costs computed by TransferWithCosts

---

psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/execution.py

Do not reuse variable name for different type.
Use 'Callable' instead of 'callable' to annotate callable argument type

llvm: Type annotation fixes

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py

Use get_random_state_ptr helper in GridSearch function instead of accessing the random state directly.
The helper handles reseeding the random state if the seed has changed.
Remove unneeded parameters from compiled structures; read-only parameters with custom getters are user-only and not used in compilation.

llvm: Reduce overhead of compiled parameters

---

psyneulink/core/components/functions/nonstateful/objectivefunctions.py
psyneulink/core/globals/utilities.py
tests/functions/test_distance.py

Consolidate tests:
* Drop unused ANGLE metric
* Add test for DOT_PRODUCT metric
Consolidate Python execution paths of different metrics.
Turn "NORMALIZE" into compiled parameter.

llvm, Distance: Turn "NORMALIZE" into compiled parameter

---

broken_trans_deps.txt

modeci_mdf available on python 3.11 doesn't set the provider to use as required by onnxruntime 1.16

deps: Don't use onnxruntime==1.16 on python 3.11

---

.github/workflows/codeql.yml

Restrict the fetch depth to 100 entries to save space.
Cleanup pip cache after installing pnl.

ci/codeql: Reduce disk space usage

---

psyneulink/core/llvm/helpers.py
tests/llvm/test_helpers.py

libc printf only supports fp64 and expects other float types to be extended to fp64.

llvm: Add support for fp32 to printf helper

---

.github/workflows/pnl-ci.yml
requirements.txt

Only for dependencies that have lower bounds.
Bump lower bounds to pass tests.

ci/github-actions: Add CI run using lowest supported version of dependencies

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py

A new OneHot instance is created in the constructor if needed. So the default one is either unused or replaced.

SoftMax: Switch default one_hot_function to 'None'

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/combinationfunctions.py
psyneulink/core/components/functions/nonstateful/distributionfunctions.py
psyneulink/core/components/functions/nonstateful/objectivefunctions.py
psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py
psyneulink/core/components/functions/userdefinedfunction.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/builder_context.py
psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py

Remove parameters blocked by structural parameters from compiled structures.
Add tracking of parameters used in compiled structures and assert that all those included are used.
Unify parameter and state substructure retrieval API.

llvm: Minimize and track parameters used in compiled structures

---

psyneulink/core/compositions/composition.py

Include all constructor attributes, not just conditions:
- default_execution_id
- mode
- default_absolute_time_unit
For example, setting of Scheduler.mode using argument scheduling_mode to Composition.run would not persist across Scheduler rebuilds.

Composition: correct rebuilding scheduler on graph change

---

psyneulink/core/globals/utilities.py
psyneulink/core/scheduling/__init__.py
psyneulink/core/scheduling/condition.py
psyneulink/core/scheduling/scheduler.py
requirements.txt
tests/composition/test_composition.py
tests/documentation/test_module_docs.py
tests/mdf/test_mdf.py
tests/scheduling/conftest.py
tests/scheduling/test_scheduler.py

- correct bug in autogenerating pnl Conditions from graph-scheduler Conditions
- modify Scheduler wrappers to support both basic and structural Conditions
- add wrappers for new graph_scheduler.Scheduler methods:
- remove_condition
- add_graph_edge
- remove_graph_edge
- update requirements to graph-scheduler<1.3.0 to include graph structure conditions release

Support graph-scheduler graph structure conditions

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/test-release.yml

This reverts commit a73ab288e91da1ef4f2b2557110f2af86f6d51bd.
v4 fails to download documentation artifacts.

Revert "github-actions(deps): bump actions/download-artifact from 3 to 4 (#2865)"

---

psyneulink/core/components/functions/nonstateful/fitfunctions.py
tests/composition/test_parameterestimationcomposition.py

Replacing `sampler._rng`, as done in `PECOptimizationFunction`, only works for `optuna.RandomSampler`.

tests: Seed optuna samplers

---

psyneulink/core/globals/mdf.py
tests/mdf/model_backprop.py
tests/mdf/test_mdf.py

globals/locals state was incorrectly shared between reference and test model output due to use of eval/exec, resulting in falsely passing tests

tests: MDF: correct use of shared state

---

broken_trans_deps.txt

The following packages need at least sphinx-5 without indicating it in dependencies:
* sphinxcontrib-applehelp >=1.0.8,
* sphinxcontrib-devhelp >=1.0.6,
* sphinxcontrib-htmlhelp >=2.0.5,
* sphinxcontrib-serializinghtml >=1.1.10,
* sphinxcontrib-qthelp >=1.0.7

deps: Block sphinxcontrib-* that silently depend on sphinx >=5

---

psyneulink/core/components/functions/nonstateful/combinationfunctions.py
psyneulink/core/components/functions/nonstateful/objectivefunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/components/ports/port.py
setup.cfg
tests/composition/test_composition.py
tests/composition/test_control.py
tests/composition/test_learning.py
tests/functions/test_memory.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_lca.py
tests/mechanisms/test_mechanisms.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/projections/test_projection_specifications.py

A collection of minor fixes and updates improves the handling of warnings by updating tests to use new interfaces.
The original distribution of warnings when running 4 test jobs was 7299 emitted warnings in 211 locations:
5 DeprecationWarning
9 FutureWarning
1 MatplotlibDeprecationWarning
4 PendingDeprecationWarning
12 PNLCompilerWarning
2 PytestBenchmarkWarning
1 PytestRemovedIn8Warning
1 PytestReturnNotNoneWarning
4 RuntimeWarning
1 SyntaxWarning
171 UserWarning
Changes in this PR reduce this to 5696 emitted warnings in 191 locations:
2 FutureWarning
1 MatplotlibDeprecationWarning
4 PendingDeprecationWarning
12 PNLCompilerWarning
2 RuntimeWarning
170 UserWarning
Individual commits target different warning classes.

Reduce number of warnings emitted during testing

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

Restrict upload of "pr_number" artifact to "base" job, it only runs in pull_requests and there is only one such job.
Add version restriction to the name of test result artifact.
Do not upload built dist packages for "min" version test run, they are not different from the standard run.

ci/github-actions: Make sure the uploaded artifacts are unique

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml

Both need to be updated together, operations using mismatched combination fail.

ci/ga: Bump versions of actions/{download,upload}-artifact

---

.github/workflows/pnl-ci.yml

Split numpy info from OS machine info.

ci/ga: Print additional CPU and memory info on all runners

---

.github/workflows/pnl-ci.yml

Runners are running in a VM and test workers running on all vCPUs might get better performance than bare metal threads depending on the hypervisor vCPU scheduling.

ci/ga: Use all logical cores to run tests

---

tests/composition/test_learning.py

It doesn't transfer to tests using the fixture (and does nothing).
Apply marks to parameters instead.

tests/autodiff: Do not apply marks to a fixture

---

psyneulink/core/components/component.py

Numpy builtins change type in numpy-1.25+ which converted Python dispatcher function to C dispatcher in:
60a858a372b14b73547baacf4a472eccfade1073
("ENH: Improve array function overhead by using vectorcall")
Check for np.sum type to exclude parameters of this type from compiled structures.

llvm/component: Explicitly check for numpy array functions

---

psyneulink/core/components/component.py

Numpy functions like np.sum are no longer of type FunctionType since Numpy moved dispatcher implementation to C in 1.25 [0,1]
Add "type(np.sum)" in addition to types.FunctionType to  use the same path for Nnumpy functions in numpy 1.25.
[0] https://github.com/numpy/numpy/commit/60a858a372b14b73547baacf4a472eccfade1073
[1] https://github.com/numpy/numpy/issues/24019
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2908

mdf: Encode numpy functions the same as Python functions

---

Scripts/Debug/stability_flexibility/stability_flexibility.py
Scripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py
psyneulink/core/compositions/parameterestimationcomposition.py
tests/composition/test_parameterestimationcomposition.py

It turns out the that PEC code was assuming the inner compositions port map dict order was always the same as the output ports list. This was non-deterministic it seems. Now we Get the index of the outcome variable in the output ports of inner composition. To do this, we must use the inner composition's portmap to get the CIM output port that corresponds to the outcome variable.

Fix bug in PEC mapping outcomes variables to data.

---

conftest.py
psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py

Cleanup the function that filters compilable parameters.
Restrict the writeback function to always work on compiled state (RW params).

llvm: Move learnable matrices from RO params to RW params

---

conftest.py
psyneulink/core/llvm/execution.py
tests/functions/test_memory.py

AUtomatically writeback parameters for compiled tests.

llvm: Enable state writeback on all compiled Functions and Mechanisms

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/execution.py
psyneulink/library/components/mechanisms/processing/transfer/recurrenttransfermechanism.py

Remove explicit inclusion of the recurrent projection in the compiled structures.
Filter out Autoassociative projections from the list of composition projections.

llvm: AutoassociativeProjection is a PNL param of the Mechanism

---

README.rst
Scripts/Models (Under Development)/Bustamante_Stroop_XOR_LVOC_Model_VZ.py
docs/source/index.rst
docs/source/index_logo_with_text.rst
psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/globals/utilities.py
psyneulink/library/compositions/gymforagercfa.py
psyneulink/library/compositions/regressioncfa.py
requirements.txt
tests/composition/test_control.py

The replaces autograd with PyTorch `torch.func.grad` in GradientOptimization. It also removes references to it in a few other places. There is currently only one test that exercises autograd and this seems to pass using PyTorch.

Remove autograd

---

.github/workflows/pnl-ci.yml

Windows x86 ci runs can fail because the container runs out of memory
during testing. This is caused by memory leaks in psyneulink and limited
available memory on the containers. As a workaround, running the full
set of tests over multiple jobs reduces peak memory usage.
Three jobs replace the original Windows x86 build, running pytest with:
1. -m llvm
2. -m "not llvm and composition"
3. -m "not llvm and not composition"
Jobs with the same OS, python version, and architecture overwrite
uploaded dist packages.

ci: split windows x86 job

---

psyneulink/core/llvm/codegen.py
tests/mechanisms/test_ddm_mechanism.py

Otherwise the evaluation of "is_finished" is different in the mechanism
execution, and evaluation of scheduling conditions.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2931

llvm, node_wrapper: Allow modulatory projections for "is_finished" wrapper

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/userdefinedfunction.py

- allow creating instance-level `Parameter`s from arguments to Component constructors
- use normal Parameter parsing/setting for UserDefinedFunction custom parameters

UserDefinedFunction custom parameter improvements

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

macos-latest now uses macos-14 on M1 (arm64) runners.
Use native python-architecture in these jobs.

ci/ga: Use native python version on macos-arm64 runners

---

.github/workflows/pnl-ci-docs.yml

Generate the base vs. head job matrix dimension dynamically.

ci/ga: Simplify documentation CI jobs

---

docs/source/Cohen_HustonModel.rst
docs/source/ConventionsAndDefinitions.rst
docs/source/MontagueModel.rst
docs/source/NieuwenhuisModel.rst
docs/source/PCTC_model.rst
psyneulink/core/components/component.py
psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/components/mechanisms/modulatory/control/gating/gatingmechanism.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/components/mechanisms/modulatory/learning/learningmechanism.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/components/ports/modulatorysignals/learningsignal.py
psyneulink/core/components/ports/modulatorysignals/modulatorysignal.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/components/ports/port.py
psyneulink/core/compositions/composition.py
psyneulink/core/compositions/parameterestimationcomposition.py
psyneulink/core/compositions/pathway.py
psyneulink/core/compositions/showgraph.py
psyneulink/core/globals/parameters.py
psyneulink/library/components/mechanisms/modulatory/learning/autoassociativelearningmechanism.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/components/mechanisms/processing/integrator/episodicmemorymechanism.py
psyneulink/library/components/mechanisms/processing/transfer/contrastivehebbianmechanism.py
psyneulink/library/components/mechanisms/processing/transfer/kohonenmechanism.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/emcomposition.py

Fix the following warnings:
WARNING: Malformed table. (3 instances)
WARNING: Title underline too short. (13 instances)
WARNING: Inline strong start-string without end-string. (31 instances)
WARNING: Inline literal start-string without end-string. (1 instance)
WARNING: Inline emphasis start-string without end-string. (2 instances)
WARNING: Unknown target name (3 instances)
WARNING: Inline interpreted text or phrase reference start-string without end-string. (31 instances)
WARNING: Inline substitution_reference start-string without end-string. (1 instance)
The above removes 61/81 instances of `<span class="problematic">` in the generated html.

docs: Fix basic rst formatting errors

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/ports/outputport.py
psyneulink/core/globals/keywords.py
psyneulink/core/globals/parameters.py
psyneulink/core/globals/utilities.py
psyneulink/library/compositions/pytorchwrappers.py

During deepcopy of `Component`s, we still shallow copy most attributes that are `Component`s to treat them like pointers instead of objects.
Only do instance checks within `Component.__deepcopy__`, because this reduces time checking the type of non-Component objects (which we do not need to hybrid copy), will work outside of calls to `copy_parameter_value`, and avoids the need to manually construct hybrid copies of (possibly nested) iterables.

Component: faster copying

---

.github/workflows/pnl-ci.yml

Use vars object in "runs-on" directly.
Drop the select-runner preamble job.

ci/ga: Use single variable to check for self-hosted runners availability

---

tests/composition/test_parameterestimationcomposition.py
tests/mechanisms/test_ddm_mechanism.py

Fixes: efc07fc76e14fc62d0687a34c59c6691dc8f3b69
("llvm, node_wrapper: Allow modulatory projections for "is_finished" wrapper")

tests: Add missing 'composition' marks

---

psyneulink/core/llvm/execution.py

The values in CPU buffers can change via updates to Python Parameters. GPU buffers thus have to be updated/recreated on every launch.
Similarly, Python Parameters can access the most recent value, so modified buffers have to be downloaded after kernel execution.
Fixes PTXExec and PTXRun failures in the new `test_multiple_runs_with_parameter_change*` tests.

llvm/cuda: Synchronize CPU and GPU buffers

---

.github/workflows/pnl-ci.yml
conftest.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/builder_context.py
requirements.txt
tests/composition/test_composition.py

Clear graph-scheduler caches after every test.
Create a copy of the scheduler condition in composition to avoid leaking a reference to a global instance.
Restore a single run of x86 CI testing.
Add a check for destruction of compiled structures at the end of each compiled test.

Fix reference leaks and add compiled cleanup destruction check

---

conftest.py
psyneulink/core/components/functions/function.py
psyneulink/core/globals/parameters.py
psyneulink/core/llvm/execution.py

Use a helper function for recursive synchronization of the compiled structures.
Use `ctypes` type instead of value in a call to `sizeof` (`sizeof` builtin types throws an exception).
Exclude Time and Optimizer custom classes from writeback.
Do not invalidate PRNG when syncing compiled seed value.
Make the synchronization methods private, drop explicit synchronization in Function and Mechanism tests.
Restrict shape changes on synchronization to known cases of 0d arrays and 'matrix' Parameters.

llvm: Consolidate construction and sync of compiled structures

---

.github/workflows/pnl-ci-docs.yml
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
tests/composition/test_learning.py

Drop macos python3.7 documentation ci job.
Fix codestyle errors detected by new pycodestyle

Codestyle and CI macos py3.7 docs

---

Scripts/Models (Under Development)/bi-percepts.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/library/compositions/regressioncfa.py
tests/functions/test_combination.py
tests/functions/test_integrator.py
tests/models/test_bi_percepts.py

Call itertools.product with the module qualifier.
Use np.prod instead of np.product.

treewide: Qualify calls to `product`

---

tests/llvm/test_debug_composition.py

Restores old value of PNL_LLVM_DEBUG even in case of error.

tests/debug_composition: Use fixture to preserve environment

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
psyneulink/core/llvm/builtins.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/helpers.py

Make MT state size 8B aligned.
Make Philox state size 8B aligned.
Use derived types in operations where the expected type is known.
Codestyle.

llvm: Tweaks to structure layout and codestyle

---

psyneulink/core/components/component.py
psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/execution.py
tests/mechanisms/test_recurrent_transfer_mechanism.py

Disable special setter logic when syncing compiled parameters.
Cache both ctype instance and numpy instance for compiled execution.
Switch CUDA execution to use numpy variants of compiled structures.

llvm: Create numpy structures of all params/state before syncing to Parameters

---

psyneulink/core/components/mechanisms/processing/transfermechanism.py
psyneulink/core/llvm/builder_context.py
tests/composition/test_composition.py

Enums are represented as 0-d integer arrays and the Parameter type changes to 0-d integer array after compilation sync. Make sure the new value type can be consumed by the follow-up compiled, or Python, execution.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/2984

llvm: Fix processing of enum values after compilation sync

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/llvm/__init__.py
tests/misc/test_leak.py

Do not call GC in llvm leak check unless it is needed.
Cleanup test_composition_leak.
Add show_graph operations to test_composition_leak.
Drop beartype decorator from a function internal to a mechanism method.

tests: Extend and cleanup the leak test

---

psyneulink/core/llvm/execution.py

Only the ArgumentHandler class provides the .array member that is used to check if a gpu_buffer is not stale.
Fixes: 36e52b8ceb50d69c04d8e9aa81cd2139f27f01ee
("llvm/execution/cuda: Use numpy argument handlers to access
compiled structures")

llvm/execution/cuda: Always use pycuda ArgumentHandler as cached buffer

---

psyneulink/core/components/ports/port.py

• port.py:
_parse_port_spec():  enhance error message for bad MECHANISM entry in modulatory param specification

• port.py:

---

psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/codegen.py
psyneulink/core/llvm/execution.py
psyneulink/core/llvm/helpers.py

Remove workaround in used parameters check. Unused parameters should be added to the blocklist in Component.
Rename node_wrapper -> node assembly to avoid confusion with wrapped nodes.

llvm: Remove workaround, rename node assembly

---

psyneulink/core/llvm/__init__.py
tests/llvm/test_builtins_intrinsics.py
tests/llvm/test_builtins_matrix.py
tests/llvm/test_builtins_vector.py

'_type_' special attribute stores pointee type for pointers [0], array element type for arrays[1], but string type representation for other types.
Adjust builtin tests to not rely on byref_arg_types of non-pointer arguments. Cleanup codestyle in builtin tests.
Use np.sum() instead of sum() to keep the result in the same precision as the input array.
[0] https://docs.python.org/3/library/ctypes.html#ctypes._Pointer._type_
[1] https://docs.python.org/3/library/ctypes.html#ctypes.Array._type_

llvm: Store only pointee types in byref_arg_types for pointer arguments

---

requirements.txt
tests/composition/test_parameterestimationcomposition.py

Set the minimum SciPy version to the last version that supports Python 3.7.
Adjust expected results in the differential evolution test based on SciPy version.
Increase upper bound from <1.12 to <1.15.

requirements: Update scipy requirements from <1.12 to >=1.7.3, < 1.15.0

---

psyneulink/core/llvm/helpers.py
tests/llvm/test_helpers.py

Assert on invalid paths.
Add test for integer type conversion.

llvm: Improve test coverage of compilation helpers

---

psyneulink/core/components/mechanisms/processing/integratormechanism.py
tests/components/test_component.py

size is used only as fallback for default_variable, but IntegratorMechanism always explicitly passed up a default_variable, even if not passed in during construction

IntegratorMechanism: correct broken size argument

---

README.rst
docs/source/index.rst

`pip install example[example]` doesn't work in all shells but `pip install "example[example]"` works consistently.

docs: add quotation to pip install

---

psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/nonstateful/combinationfunctions.py
psyneulink/core/components/functions/nonstateful/distributionfunctions.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/components/ports/modulatorysignals/controlsignal.py
psyneulink/core/compositions/report.py
psyneulink/core/scheduling/condition.py
psyneulink/library/components/mechanisms/processing/integrator/ddm.py
psyneulink/library/compositions/regressioncfa.py

Reduces number of warnings from ~84000 -> ~11000 (~87%)

treewide: Use ndarray.item() to convert single element numpy arrays to scalars

---

psyneulink/core/components/functions/nonstateful/selectionfunctions.py
tests/functions/test_selection.py

It still doesn't match the current Python behaviour but matches new Python modes to be introduced.
Return absolute value in MIN_ABS_VAL mode.
Refactor tests to include names on the same line as test parameters.

llvm/OneHot: Return first extreme value rather than the last

---

docs/Makefile

find -exec does not propagate errors.

docs: Use pattern rule to execute generator scripts

---

psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/builtins.py
psyneulink/core/llvm/debug.py
psyneulink/core/llvm/helpers.py
psyneulink/core/llvm/jit_engine.py
psyneulink/library/compositions/compiledoptimizer.py
psyneulink/library/compositions/pytorchwrappers.py
tests/llvm/test_debug_composition.py
tests/llvm/test_helpers.py

Use per jit-engine printf pointer to not crash printf calls on GPU.
Replace 'overrride_debug' with tags and allow dynamic control via PNL_LLVM_DEBUG env var.

llvm: Control debug output via PNL_LLVM_DEBUG env var

---

conftest.py

Needed to pass fixture 'isinstance' checks introduced in pytest-benchmark-5.0.0.

conftest: Inherit the original class of the benchmark fixture

---

Scripts/Debug/stability_flexibility/stability_flexibility_pec_optimize.py
psyneulink/core/components/functions/nonstateful/fitfunctions.py
requirements.txt
tests/composition/test_parameterestimationcomposition.py

Some small modifications to PEC\Optuna RNG seeding interface based on suggestions from @jvesely and @jdcpni.
- Hack was removed that set optuna RandomState object under the hood.
- Added ability to pass un-instantiated optuna sampler to `PECOptimizationFunction` and added an argument called `optuna_kwargs` for specifying any desired sampler construction args. This allows use the PEC `initial_seed` if it is specified. 
- Added a warning to the user if they have specified a PEC `initial_seed` with an already instantiated optuna sampler. 
Fixes issue #2874

Clean up interface to for specifying seeds to optuna samplers with PEC.

---

psyneulink/_version.py
psyneulink/core/compositions/composition.py
psyneulink/core/compositions/showgraph.py

- change subdirectory from "show_graph OUTPUT" or "show_graph output" to "pnl-show_graph-output"
- use pathlib to make directory/file names
- avoid using python site-packages dir as a default if psyneulink is installed as non-editable

showgraph: rework output directory use and defaults

---

psyneulink/core/components/functions/nonstateful/fitfunctions.py
requirements.txt

fastkde 2.x uses underscores in keyword params rather than camelCase.
versions 2.0.0 and 2.0.1 are available for all covered python versions (3.7-3.12)

requirements: Bump fastkde to 2.x

---

.github/actions/install-pnl/action.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

Use wheel package to install psyneulink instead of using editable install.
Provide paths in install-pnl action outputs.
Use install-pnl outputs to upload the hwheel/sdist.

ga: Move wheel/sdist creation to install-pnl action

---

conftest.py
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/core/llvm/execution.py
psyneulink/core/llvm/jit_engine.py
tests/composition/test_composition.py

llvm/gpu: Use more aggressive optimizations for GPU target

---

psyneulink/core/scheduling/scheduler.py

Do not set _user_specified_conds in __init__,
because it will be set by add_condition_set
in graph_scheduler.Scheduler.__init__. This second call would result in the condition replacement warning for any conditions passed in.

Scheduler: fix false add_condition replace warning

---

psyneulink/core/globals/parameters.py

Parameter.set checks for Component values assigned after its owning Component's __init__ so that the assigned Components can be shaped compatibly and set up for later context initialization.
Check for ContextFlags.INITIALIZED initialization_status instead of is_initialized, because is_initialized also considers any initialization context, not just the status of having completed Component.__init__

Parameter: correct .set post-initialization check

---

tests/models/test_documentation_models.py

Searching for the model scripts starting from the test directory can fail if psyneulink is not installed locally. Starting from the psyneulink root directory should be more reliable across install types.

tests: models: find model script paths relative to psyneulink root

---

psyneulink/core/components/functions/nonstateful/transferfunctions.py
psyneulink/core/components/functions/nonstateful/transformfunctions.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/pytorchwrappers.py

This implements the use in pytorch of the actual Functions assigned to
the input ports. When the pytorch-equivalent of a psyneulink Function
(via _gen_pytorch_fct) is unavailable, an error is thrown.

pytorch: implement input port function execution

---

psyneulink/core/components/mechanisms/mechanism.py
tests/mechanisms/test_mechanisms.py

Calling Mechanism.execute with no input uses the Mechanism's defaults.variable as input. This was passed in without creating a copy, which resulted in defaults.variable sharing memory with an InputPort.variable, which could result in silent changes to the Mechanism's defaults.variable.

Mechanism: fix execute with no input causing shared default variable memory

---

psyneulink/core/compositions/composition.py
psyneulink/library/compositions/pytorchwrappers.py
tests/composition/test_composition.py

mods to docstring
• test_composition.py
- test_remove_node(): uncomment conditions

• patch_for_bias_nodes

---

.github/actions/install-pnl/action.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml
requirements.txt
setup.py

Bump minimum rich requirement.
Restrict 32-bit job to last available wheels.
Drop Python3.7 CI jobs.
Bump minimum Python requirement to 3.8

Drop support for python 3.7

---

psyneulink/library/models/MontagueDayanSejnowski96.py
requirements.txt

Plain names are deprecated in matplotlib and removed in matplotlib==3.8.0.
The versioned name with underscore was introduced in matplotlib==3.7.0, 6608eedfc6f33f723f1e13c6025a5b918c7c9f6d
("Re-rename builtin seaborn styles to not include a dot.")

models/MontagueDayanSejnowski: Use versioned seaborn style

---

psyneulink/core/components/component.py
psyneulink/core/components/functions/function.py
psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/globals/utilities.py
psyneulink/core/llvm/builder_context.py
psyneulink/core/llvm/execution.py
tests/composition/pec/test_stab_flex_pec_fit.py
tests/composition/test_composition.py
tests/composition/test_control.py
tests/functions/test_buffer.py
tests/llvm/test_helpers.py
tests/mechanisms/test_control_mechanism.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_processing_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/models/test_greedy_agent.py
tests/scheduling/test_scheduler.py

It is not available in Numpy 2+[0] and is mostly not necessary.
[0] https://numpy.org/devdocs/numpy_2_0_migration_guide.html#main-namespace

treewide: Don't use numpy asfarray

---

psyneulink/core/llvm/builder_context.py

Work the same way as the old "Pointer" class,
the class itself is modified to represent opaque pointers.
Neeed for llvmlite>=0.44.0

llvm: Add support for LLVM-15 typed pointers

---

psyneulink/core/components/ports/parameterport.py

Parameter getters may not be valid when called on a Parameter owned by a
type. In this case, use the default value to determine if the
Parameter can be associated with a ParameterPort.
Do not catch exceptions on instantiated classes.

ParameterPort: handle more getter errors during enumeration

---

psyneulink/core/globals/utilities.py
setup.cfg

Numpy 1.25.0 moved warnings and errors to a submodule[0]. Moreover, they are removed from the top level namespace in later versions of Numpy[1].
Add and use exception import that either points to the new exception submodule, or the global namespace depending on whether the former is available.
[0] https://numpy.org/doc/2.1/release/1.25.0-notes.html#numpy-now-has-an-np-exceptions-namespace
[1] https://numpy.org/doc/2.1/release/2.0.0-notes.html#numpy-2-0-python-api-removals

utilities: Allow Numpy warnings from numpy.exceptions

---

conftest.py
docs/source/Compilation.rst
psyneulink/core/compositions/composition.py
psyneulink/core/llvm/__init__.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/compositionrunner.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_composition.py
tests/composition/test_control.py
tests/composition/test_learning.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_mechanisms.py
tests/mechanisms/test_recurrent_transfer_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/models/test_greedy_agent.py
tests/ports/test_output_ports.py
tests/scheduling/test_condition.py
tests/scheduling/test_scheduler.py

Make most compiled modes private for test/development use only.
Introduce a new _LLVMPerNode execution mode.
Do not fall back to per-node mode in automatic fallback.
Use ExecutionMode helper methods rather than COMPILED mask to determine compiled mode.

llvm; Refactor ExecutionMode handling

---

conftest.py
psyneulink/core/components/functions/stateful/integratorfunctions.py
psyneulink/core/components/functions/stateful/statefulfunction.py
psyneulink/core/components/mechanisms/mechanism.py
tests/functions/test_integrator.py
tests/mechanisms/test_ddm_mechanism.py
tests/mechanisms/test_processing_mechanism.py
tests/mechanisms/test_transfer_mechanism.py

Return the value of "previous_value" Parameter in Function "reset" variant for Functions that don't have other Parameters with initializers.
Return the values of "previous_value" and "previous_time" in DriftDiffusionIntegrator "reset" variant".
Update output ports in Mechanism "reset" execution variants, using the value returned from the Function's "reset" variant.
Update tests to allow the selection of execution variants for Mechanisms and Functions.
Add reproducer from https://github.com/PrincetonUniversity/PsyNeuLink/issues/3142 as a regression test.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/3142

llvm: Return initialized values as output from "reset" function execution variants.

---

.github/actions/install-pnl/action.yml

Fixes: 41b254d284afb1daad6a890f9c11c57799c1a1f1
("ga: Move wheel/sdist creation to install-pnl action (#3085)")

ci/ga: setup.py generates sdist packages with .tar.gz extension

---

psyneulink/core/components/functions/nonstateful/optimizationfunctions.py
setup.cfg

Itertools classes won't support copy or pickle starting in Python 3.14 Filter the associated DeprecationWarning.
Fixes ~5000 warnings in a full test run.

OptimizationFunction: Wrap itertools.product in a generator

---

psyneulink/core/compositions/composition.py
tests/composition/test_composition.py

Only explicitly specified FEEDBACK projections are known to Composition.graph. FLEXIBLE projections are determined to be FEEDBACK or NON_FEEDBACK in Composition.graph_processing.

Composition: fix feedback_projections property

---

psyneulink/core/compositions/composition.py
psyneulink/library/compositions/autodiffcomposition.py
tests/composition/test_composition.py

- other Components generally set in their execute methods
- setting in Composition.run fails to set when a Composition is nested, because only execute gets called

Composition: set most_recent_context in execute, not run

---

tests/composition/test_autodiffcomposition.py

Fixes: `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first. When the test_training_xor_with_batching test is run on a CUDA enabled machine.`
Fixes: beebd2a968fbeebc45e93d9785460a1c1860686a
("Add support for batching to AutoDiffCompostion in PyTorch mode. (#3204)")

tests/AutodiffComposition: Explicitly copy tensors to CPU before converting to numpy

---

psyneulink/core/components/functions/stateful/memoryfunctions.py
psyneulink/core/globals/utilities.py
psyneulink/library/compositions/autodiffcomposition.py
psyneulink/library/compositions/emcomposition.py
requirements.txt
tests/functions/test_distance.py
tests/mdf/model_with_control.py

Don't call np.all on a generator.
Use greedy regexp match to remove function/construction call arguments.
Use convert_to_np_array helper in AutodiffComposition.
Explicitly check for empty arrays when converting ContentAddressableMemory weights to integers.
Allow the latest numpy and fastkde packages.
Closes: https://github.com/PrincetonUniversity/PsyNeuLink/issues/3205

deps: Fix issues and enable Numpy 2+

---

.github/actions/install-pnl/action.yml

Recent versions don't provide win32 wheels.

ci/ga: Restrict fastkde in x86 runs

---

.github/workflows/test-release.yml
MANIFEST.in
README.rst
docs/source/index.rst
setup.cfg
setup.py

- use pypa/build instead of setup.py to build
- correct deprecated/old setup.cfg settings
- run `twine check --strict` on distfiles before uploading
- fix problems uploading to github releases in test-release workflow

maint: update setup and build config, and release workflow

---

broken_trans_deps.txt

Some packages, like torch, stopped providing macos x86_64 wheels and the last version is compiled using Numpy 1.x.
These packages don't work with Numpy 2, although Numpy 2 is available for macos x86_64.
On the other hand, binary packages built with Numpy 2+ work OK on older versions of Numpy.

broken_trans_deps: Restrict numpy to <2 on macos x86_64

---

psyneulink/core/components/component.py
psyneulink/core/components/projections/projection.py
psyneulink/library/compositions/autodiffcomposition.py

This PR adds get_target() to AutodiffComposition as an override, that calls infer_backpropagation_learning_pathways() 
in order determine TARGET Nodes for the Composition to be returned.

• autodiffcomposition.py

---

.github/workflows/pnl-ci.yml
tests/composition/pec/test_stab_flex_pec_fit.py
tests/composition/test_autodiffcomposition.py
tests/composition/test_composition.py
tests/composition/test_control.py
tests/composition/test_emcomposition.py
tests/composition/test_grucomposition.py
tests/functions/test_integrator.py
tests/mechanisms/test_episodic_memory.py
tests/mechanisms/test_integrator_mechanism.py
tests/mechanisms/test_transfer_mechanism.py
tests/misc/test_parameters.py
tests/scheduling/test_scheduler.py

There were several cases of unused arguments in test functions:
* Test names in test parameters. These were converted to use pytest.param(..., id=name) instead
* A fixture with unused value was converted to 'usefixture' decorator.
* Unused autoparametrizing fixture. This would execute identical tests multiple times. The use of fixture was removed.
* Unused parametrized arguments. These would lead to multiple executions of identical tests. These were converted to reduced parametrization instead.
The primary motivation was to avoid multiple executions of identical tests in the cases of undue parametrized arguments or auto-parametrizing fixtures, the other cases were modified to allow automatic enforcement.
Automatic enforcement was added in the form of flak8 linter that checks for unused …

tests: Drop unused function arguments

---

tests/composition/test_report.py

rich prints varying amounts of padding characters depending on the real terminal width, and assertions check against strings generated with a certain terminal width

tests: set fixed terminal width for report testing

---

.github/actions/install-pnl/action.yml
.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml
.github/workflows/test-release.yml
doc_requirements.txt
psyneulink/core/globals/mdf.py
psyneulink/core/scheduling/scheduler.py
setup.py
tests/mdf/test_mdf.py

Adapt test.
Advertise support for Python 3.13.
Add CI workarounds to build onnx-1.17.0.
Enable Python 3.13 CI jobs.

Add support for Python 3.13

---

psyneulink/library/components/mechanisms/processing/transfer/lcamechanism.py
tests/mechanisms/test_lca.py

Values of 0 would be replaced by the class default (_parse_threshold_args is called before full initialization).
Fixes #3264

LCAMechanism: do not assign default termination_threshold if evals False

---

.github/workflows/pnl-ci.yml

Test open pdf during execution, which on Windows is handled by msedge.
msedge is also a suspect that intermittently prevents Windows CI jobs.

ci/ga: Stop 'msedge' at the end of windows jobs

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

Windows runners use MS Edge as the default pdf viewer.
This causes issues if any of the tests calls show_graph()
or any other routine that by default produces a .pdf file
and opens is in the default application.
The problem with MS Edge is that it intermittently fails
to exit and hangs the entire CI job in the last step.
see: https://github.com/actions/runner/issues/3383
Removing the default .pdf file association on windows is
quite difficult because it needs to check multiple places
and elevated privileges.
Installing an alternative pdf viewer works around the issue
as it prevents MS Edge from running when .pdf is displayed.

ci/ga: Install alternative pdf viewer on windows runners

---

psyneulink/core/globals/parameters.py
psyneulink/core/globals/utilities.py

True by default
if set to False, any otherwise numeric arrays that contain booleans
will use object dtype and will not convert the booleans to numbers

Parameter: add bool_as_number flag

---

psyneulink/core/components/mechanisms/mechanism.py
psyneulink/core/globals/utilities.py
psyneulink/core/llvm/builder_context.py
tests/misc/test_user_seed.py

The PNL global seed is initialized as np.uint32, but can be replaced by any other type by calling the `set_global_seed` function.
This creates issues during compilation as the seed needs to be represented as a float to support modulation.
Moreover, the issue manifests in a confusing way as a failed assertion that a Port other than OutputPort sees a data type mismatch between the existing and modulated value.
Add an assertion message better explaining the asserted failure.
Explicitly convert 'seed' and 'function-seed' parameter values to float when deriving compiled data types.
Convert the new seed value passed to `set_global_seed` to match the data type of the current seed (np.uint32) and add a new test to check the behaviour.
Cleanup and improve comments in the affected code paths.

llvm: Disambiguate seed data type

---

.github/workflows/pnl-ci-docs.yml
.github/workflows/pnl-ci.yml

This reverts commit bf914fd3d355c49a2e7f441df3f8b151c312c790.
modeci_mdf-0.4.13 no longer pins the onnx version.
The workaround is no longer necessary.

Revert "ci/ga: Fallback to macos-14 for python-3.13 (#3341)"
